# Copyright (C) 2014-2022  CEA/DEN, EDF R&D
#
# This library is free software; you can redistribute it and/or
# modify it under the terms of the GNU Lesser General Public
# License as published by the Free Software Foundation; either
# version 2.1 of the License, or (at your option) any later version.
#
# This library is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
# Lesser General Public License for more details.
#
# You should have received a copy of the GNU Lesser General Public
# License along with this library; if not, write to the Free Software
# Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307 USA
#
# See http://www.salome-platform.org/ or email : webmaster.salome@opencascade.com
#

from salome.shaper import model

model.begin()
partSet = model.moduleDocument()
Part_1 = model.addPart(partSet)
Part_1_doc = Part_1.document()
model.addParameter(Part_1_doc, "BHD", "8", "Base Hole Diameter")
model.addParameter(Part_1_doc, "BHPD", "14", "Base Hole Plate Diameter")
model.addParameter(Part_1_doc, "BHPS", "2", "Base Hole Plate Thickness")
model.addParameter(Part_1_doc, "BHPFR", "BHPS/4*3", "Base Hole Plate Fillet Radius")
Parameter_BPS = model.addParameter(Part_1_doc, "BPS", "6", "Base Plate Thickness")
model.addParameter(Part_1_doc, "Draft", "100", "Bracket Draft")
model.addParameter(Part_1_doc, "TDI", "14", "Tube Internal Diameter")
model.addParameter(Part_1_doc, "TDE", "TDI+8", "Tube External Diameter")
model.addParameter(Part_1_doc, "TL", "86", "Tube Length")
model.addParameter(Part_1_doc, "Width", "112", "Full Width of Base")
model.addParameter(Part_1_doc, "LegThick", "5")
model.addParameter(Part_1_doc, "BaseLegFillet", "3")
model.addParameter(Part_1_doc, "LegTopFillet", "2")
model.addParameter(Part_1_doc, "BottomCutFillet", "2")
Sketch_1 = model.addSketch(Part_1_doc, model.defaultPlane("YOZ"))
SketchLine_1 = Sketch_1.addLine(56, -3.652030108005817e-032, 20.9106603007908, -1.450725046594067e-032)
SketchLine_2 = Sketch_1.addLine(model.selection("EDGE", "PartSet/OY"))
SketchConstraintCoincidence_1 = Sketch_1.setCoincident(SketchLine_1.startPoint(), SketchLine_2.result())
SketchConstraintCoincidence_2 = Sketch_1.setCoincident(SketchLine_1.endPoint(), SketchLine_2.result())
SketchLine_3 = Sketch_1.addLine(20.9106603007908, -1.450725046594067e-032, 17.67553830650723, 18.34728855042577)
SketchLine_3.setName("SketchLine_33")
SketchLine_3.result().setName("SketchLine_33")
SketchLine_4 = Sketch_1.addLine(20.9106603007908, -1.450725046594067e-032, 17.3841206866215, 20)
SketchLine_4.setName("SketchLine_3")
SketchLine_4.result().setName("SketchLine_3")
SketchLine_4.setAuxiliary(True)
SketchConstraintCoincidence_3 = Sketch_1.setCoincident(SketchLine_1.endPoint(), SketchLine_4.startPoint())
SketchLine_5 = Sketch_1.addLine(15.70591356041877, 20, 0, 20)
SketchLine_5.setName("SketchLine_32")
SketchLine_5.result().setName("SketchLine_32")
SketchLine_6 = Sketch_1.addLine(17.3841206866215, 20, 0, 20)
SketchLine_6.setName("SketchLine_4")
SketchLine_6.result().setName("SketchLine_4")
SketchLine_6.setAuxiliary(True)
SketchConstraintCoincidence_4 = Sketch_1.setCoincident(SketchLine_4.endPoint(), SketchLine_6.startPoint())
SketchLine_7 = Sketch_1.addLine(model.selection("EDGE", "PartSet/OZ"))
SketchLine_7.setName("SketchLine_5")
SketchLine_7.result().setName("SketchLine_5")
SketchConstraintCoincidence_5 = Sketch_1.setCoincident(SketchLine_6.endPoint(), SketchLine_7.result())
SketchLine_8 = Sketch_1.addLine(11, 85, 24.49270766728805, 8.479052309092824)
SketchLine_8.setName("SketchLine_77")
SketchLine_8.result().setName("SketchLine_77")
SketchLine_9 = Sketch_1.addLine(27.44713044942998, 5.999999999999999, 56, 6)
SketchLine_9.setName("SketchLine_78")
SketchLine_9.result().setName("SketchLine_78")
SketchLine_10 = Sketch_1.addLine(-11, 85, -24.49270712488033, 8.479055385239919)
SketchLine_10.setName("SketchLine_79")
SketchLine_10.result().setName("SketchLine_79")
SketchLine_11 = Sketch_1.addLine(-27.44713039880284, 6, -56, 6)
SketchLine_11.setName("SketchLine_80")
SketchLine_11.result().setName("SketchLine_80")
SketchLine_12 = Sketch_1.addLine(0, 85, 11, 85)
SketchLine_12.setName("SketchLine_7")
SketchLine_12.result().setName("SketchLine_7")
SketchLine_13 = Sketch_1.addLine(11, 85, 24.92983147596873, 6)
SketchLine_13.setName("SketchLine_8")
SketchLine_13.result().setName("SketchLine_8")
SketchLine_13.setAuxiliary(True)
SketchConstraintCoincidence_6 = Sketch_1.setCoincident(SketchLine_12.endPoint(), SketchLine_13.startPoint())
SketchConstraintCoincidence_6.setName("SketchConstraintCoincidence_9")
SketchLine_14 = Sketch_1.addLine(24.92983147596873, 6, 56, 6)
SketchLine_14.setName("SketchLine_9")
SketchLine_14.result().setName("SketchLine_9")
SketchLine_14.setAuxiliary(True)
SketchConstraintCoincidence_7 = Sketch_1.setCoincident(SketchLine_13.endPoint(), SketchLine_14.startPoint())
SketchConstraintCoincidence_7.setName("SketchConstraintCoincidence_10")
SketchLine_15 = Sketch_1.addLine(56, 6, 56, -3.652030108005817e-032)
SketchLine_15.setName("SketchLine_10")
SketchLine_15.result().setName("SketchLine_10")
SketchConstraintCoincidence_8 = Sketch_1.setCoincident(SketchLine_14.endPoint(), SketchLine_15.startPoint())
SketchConstraintCoincidence_8.setName("SketchConstraintCoincidence_11")
SketchConstraintCoincidence_9 = Sketch_1.setCoincident(SketchLine_1.startPoint(), SketchLine_15.endPoint())
SketchConstraintCoincidence_9.setName("SketchConstraintCoincidence_12")
SketchConstraintHorizontal_1 = Sketch_1.setHorizontal(SketchLine_6.result())
SketchConstraintHorizontal_2 = Sketch_1.setHorizontal(SketchLine_12.result())
SketchConstraintHorizontal_3 = Sketch_1.setHorizontal(SketchLine_14.result())
SketchConstraintVertical_1 = Sketch_1.setVertical(SketchLine_15.result())
SketchConstraintAngle_1 = Sketch_1.setAngle(SketchLine_14.result(), SketchLine_13.result(), "Draft")
SketchConstraintParallel_1 = Sketch_1.setParallel(SketchLine_13.result(), SketchLine_4.result())
SketchConstraintDistance_1 = Sketch_1.setDistance(SketchLine_4.endPoint(), SketchLine_13.result(), "LegThick")
SketchConstraintDistance_2 = Sketch_1.setDistance(SketchLine_14.endPoint(), SketchLine_1.result(), 6)
SketchConstraintDistance_3 = Sketch_1.setDistance(SketchLine_6.endPoint(), SketchLine_1.result(), 20)
SketchConstraintCoincidence_10 = Sketch_1.setCoincident(SketchLine_12.startPoint(), SketchLine_7.result())
SketchConstraintCoincidence_10.setName("SketchConstraintCoincidence_13")
SketchConstraintDistance_4 = Sketch_1.setDistance(SketchLine_13.startPoint(), SketchLine_7.result(), "TDE/2")
SketchConstraintDistance_5 = Sketch_1.setDistance(SketchLine_13.startPoint(), SketchLine_1.result(), 85)
SketchConstraintDistance_5.setName("SketchConstraintDistance_11")
SketchConstraintDistance_6 = Sketch_1.setDistance(SketchLine_1.startPoint(), SketchLine_7.result(), "Width/2")
SketchConstraintDistance_6.setName("SketchConstraintDistance_12")
SketchLine_16 = Sketch_1.addLine(11, 85, 24.92983147596873, 6)
SketchLine_16.setName("SketchLine_30")
SketchLine_16.result().setName("SketchLine_30")
SketchLine_16.setAuxiliary(True)
SketchConstraintCoincidence_11 = Sketch_1.setCoincident(SketchLine_13.startPoint(), SketchLine_16.startPoint())
SketchConstraintCoincidence_11.setName("SketchConstraintCoincidence_24")
SketchLine_17 = Sketch_1.addLine(24.92983147596873, 6, 56, 6)
SketchLine_17.setName("SketchLine_31")
SketchLine_17.result().setName("SketchLine_31")
SketchLine_17.setAuxiliary(True)
SketchConstraintCoincidence_12 = Sketch_1.setCoincident(SketchLine_14.endPoint(), SketchLine_17.endPoint())
SketchConstraintCoincidence_12.setName("SketchConstraintCoincidence_25")
SketchConstraintCoincidence_13 = Sketch_1.setCoincident(SketchLine_16.endPoint(), SketchLine_13.result())
SketchConstraintCoincidence_13.setName("SketchConstraintCoincidence_26")
SketchConstraintCoincidence_14 = Sketch_1.setCoincident(SketchLine_17.startPoint(), SketchLine_14.result())
SketchConstraintCoincidence_14.setName("SketchConstraintCoincidence_27")
SketchArc_1 = Sketch_1.addArc(15.70592142426694, 18, 17.67553830650723, 18.34728855042577, 15.70591356041877, 20, False)
SketchArc_1.setName("SketchArc_2")
SketchArc_1.result().setName("SketchArc_2")
SketchArc_1.results()[1].setName("SketchArc_2_2")
SketchConstraintCoincidence_15 = Sketch_1.setCoincident(SketchArc_1.startPoint(), SketchLine_3.endPoint())
SketchConstraintCoincidence_15.setName("SketchConstraintCoincidence_28")
SketchConstraintCoincidence_16 = Sketch_1.setCoincident(SketchArc_1.endPoint(), SketchLine_5.startPoint())
SketchConstraintCoincidence_16.setName("SketchConstraintCoincidence_29")
SketchConstraintTangent_1 = Sketch_1.setTangent(SketchArc_1.results()[1], SketchLine_5.result())
SketchConstraintTangent_1.setName("SketchConstraintTangent_3")
SketchConstraintTangent_2 = Sketch_1.setTangent(SketchArc_1.results()[1], SketchLine_3.result())
SketchConstraintTangent_2.setName("SketchConstraintTangent_4")
SketchConstraintCoincidence_17 = Sketch_1.setCoincident(SketchLine_6.endPoint(), SketchLine_5.endPoint())
SketchConstraintCoincidence_17.setName("SketchConstraintCoincidence_30")
SketchConstraintCoincidence_18 = Sketch_1.setCoincident(SketchLine_4.startPoint(), SketchLine_3.startPoint())
SketchConstraintCoincidence_18.setName("SketchConstraintCoincidence_31")
SketchConstraintCoincidence_19 = Sketch_1.setCoincident(SketchLine_5.startPoint(), SketchLine_6.result())
SketchConstraintCoincidence_19.setName("SketchConstraintCoincidence_32")
SketchConstraintCoincidence_20 = Sketch_1.setCoincident(SketchLine_3.endPoint(), SketchLine_4.result())
SketchConstraintCoincidence_20.setName("SketchConstraintCoincidence_33")
SketchConstraintRadius_1 = Sketch_1.setRadius(SketchArc_1.results()[1], "LegTopFillet")
SketchConstraintRadius_1.setName("SketchConstraintRadius_7")
SketchArc_2 = Sketch_1.addArc(-15.70592142426695, 18, -15.70592154309944, 20, -17.67553694121995, 18.34729629335474, False)
SketchArc_2.setName("SketchArc_3")
SketchArc_2.result().setName("SketchArc_3")
SketchArc_2.results()[1].setName("SketchArc_3_2")
SketchLine_18 = Sketch_1.addLine(-20.91066030079081, 0, -17.67553694121995, 18.34729629335474)
SketchLine_18.setName("SketchLine_34")
SketchLine_18.result().setName("SketchLine_34")
SketchLine_19 = Sketch_1.addLine(-56, 0, -20.91066030079081, 0)
SketchLine_19.setName("SketchLine_35")
SketchLine_19.result().setName("SketchLine_35")
SketchLine_20 = Sketch_1.addLine(-56, 6, -56, 0)
SketchLine_20.setName("SketchLine_36")
SketchLine_20.result().setName("SketchLine_36")
SketchLine_21 = Sketch_1.addLine(0, 85, -11, 85)
SketchLine_21.setName("SketchLine_38")
SketchLine_21.result().setName("SketchLine_38")
SketchLine_22 = Sketch_1.addLine(-15.70592154309944, 20, 0, 20)
SketchLine_22.setName("SketchLine_40")
SketchLine_22.result().setName("SketchLine_40")
SketchConstraintHorizontal_4 = Sketch_1.setHorizontal(SketchLine_21.result())
SketchConstraintHorizontal_4.setName("SketchConstraintHorizontal_18")
SketchLine_23 = Sketch_1.addLine(-11, 85, -24.92983147596874, 6)
SketchLine_23.setName("SketchLine_37")
SketchLine_23.result().setName("SketchLine_37")
SketchLine_23.setAuxiliary(True)
SketchConstraintDistance_7 = Sketch_1.setDistance(SketchLine_23.startPoint(), SketchLine_7.result(), "TDE/2")
SketchConstraintDistance_7.setName("SketchConstraintDistance_31")
SketchLine_24 = Sketch_1.addLine(-24.92983147596874, 6, -56, 6)
SketchLine_24.setName("SketchLine_39")
SketchLine_24.result().setName("SketchLine_39")
SketchLine_24.setAuxiliary(True)
SketchConstraintHorizontal_5 = Sketch_1.setHorizontal(SketchLine_24.result())
SketchConstraintHorizontal_5.setName("SketchConstraintHorizontal_19")
SketchConstraintHorizontal_6 = Sketch_1.setHorizontal(SketchLine_19.result())
SketchConstraintHorizontal_6.setName("SketchConstraintHorizontal_20")
SketchConstraintDistance_8 = Sketch_1.setDistance(SketchLine_24.endPoint(), SketchLine_19.result(), "BPS")
SketchConstraintDistance_8.setName("SketchConstraintDistance_32")
SketchConstraintCoincidence_21 = Sketch_1.setCoincident(SketchLine_23.startPoint(), SketchLine_21.endPoint())
SketchConstraintCoincidence_21.setName("SketchConstraintCoincidence_113")
SketchConstraintDistance_9 = Sketch_1.setDistance(SketchLine_20.endPoint(), SketchLine_7.result(), "Width/2")
SketchConstraintDistance_9.setName("SketchConstraintDistance_33")
SketchConstraintCoincidence_22 = Sketch_1.setCoincident(SketchLine_24.endPoint(), SketchLine_20.startPoint())
SketchConstraintCoincidence_22.setName("SketchConstraintCoincidence_114")
SketchConstraintCoincidence_23 = Sketch_1.setCoincident(SketchLine_20.endPoint(), SketchLine_19.startPoint())
SketchConstraintCoincidence_23.setName("SketchConstraintCoincidence_115")
SketchConstraintCoincidence_24 = Sketch_1.setCoincident(SketchLine_19.endPoint(), SketchLine_18.startPoint())
SketchConstraintCoincidence_24.setName("SketchConstraintCoincidence_116")
SketchConstraintCoincidence_25 = Sketch_1.setCoincident(SketchArc_2.endPoint(), SketchLine_18.endPoint())
SketchConstraintCoincidence_25.setName("SketchConstraintCoincidence_117")
SketchConstraintVertical_2 = Sketch_1.setVertical(SketchLine_20.result())
SketchConstraintVertical_2.setName("SketchConstraintVertical_16")
SketchConstraintParallel_2 = Sketch_1.setParallel(SketchLine_23.result(), SketchLine_18.result())
SketchConstraintCoincidence_26 = Sketch_1.setCoincident(SketchLine_2.result(), SketchLine_19.endPoint())
SketchConstraintCoincidence_26.setName("SketchConstraintCoincidence_118")
SketchConstraintCoincidence_27 = Sketch_1.setCoincident(SketchLine_22.startPoint(), SketchArc_2.startPoint())
SketchConstraintCoincidence_27.setName("SketchConstraintCoincidence_119")
SketchConstraintRadius_2 = Sketch_1.setRadius(SketchArc_2.results()[1], "LegTopFillet")
SketchConstraintRadius_2.setName("SketchConstraintRadius_16")
SketchConstraintHorizontal_7 = Sketch_1.setHorizontal(SketchLine_22.result())
SketchConstraintHorizontal_7.setName("SketchConstraintHorizontal_21")
SketchConstraintCoincidence_28 = Sketch_1.setCoincident(SketchLine_22.endPoint(), SketchLine_5.endPoint())
SketchConstraintCoincidence_28.setName("SketchConstraintCoincidence_120")
SketchConstraintTangent_3 = Sketch_1.setTangent(SketchArc_2.results()[1], SketchLine_22.result())
SketchConstraintTangent_3.setName("SketchConstraintTangent_19")
SketchConstraintTangent_4 = Sketch_1.setTangent(SketchLine_18.result(), SketchArc_2.results()[1])
SketchConstraintTangent_4.setName("SketchConstraintTangent_20")
SketchConstraintAngle_2 = Sketch_1.setAngleBackward(SketchLine_19.result(), SketchLine_23.result(), "Draft")
SketchConstraintCoincidence_29 = Sketch_1.setCoincident(SketchLine_17.startPoint(), SketchLine_16.endPoint())
SketchConstraintCoincidence_29.setName("SketchConstraintCoincidence_121")
SketchArc_3 = Sketch_1.addArc(27.44713036950057, 9.000000000000002, 24.49270766728805, 8.479052309092824, 27.44713044942998, 5.999999999999999, False)
SketchArc_3.setName("SketchArc_12")
SketchArc_3.result().setName("SketchArc_12")
SketchArc_3.results()[1].setName("SketchArc_12_2")
SketchConstraintCoincidence_30 = Sketch_1.setCoincident(SketchArc_3.startPoint(), SketchLine_8.endPoint())
SketchConstraintCoincidence_30.setName("SketchConstraintCoincidence_122")
SketchConstraintCoincidence_31 = Sketch_1.setCoincident(SketchArc_3.endPoint(), SketchLine_9.startPoint())
SketchConstraintCoincidence_31.setName("SketchConstraintCoincidence_123")
SketchConstraintTangent_5 = Sketch_1.setTangent(SketchArc_3.results()[1], SketchLine_8.result())
SketchConstraintTangent_5.setName("SketchConstraintTangent_21")
SketchConstraintTangent_6 = Sketch_1.setTangent(SketchArc_3.results()[1], SketchLine_9.result())
SketchConstraintTangent_6.setName("SketchConstraintTangent_22")
SketchConstraintCoincidence_32 = Sketch_1.setCoincident(SketchLine_16.startPoint(), SketchLine_8.startPoint())
SketchConstraintCoincidence_32.setName("SketchConstraintCoincidence_124")
SketchConstraintCoincidence_33 = Sketch_1.setCoincident(SketchLine_17.endPoint(), SketchLine_9.endPoint())
SketchConstraintCoincidence_33.setName("SketchConstraintCoincidence_125")
SketchConstraintCoincidence_34 = Sketch_1.setCoincident(SketchLine_8.endPoint(), SketchLine_16.result())
SketchConstraintCoincidence_34.setName("SketchConstraintCoincidence_126")
SketchConstraintCoincidence_35 = Sketch_1.setCoincident(SketchLine_9.startPoint(), SketchLine_17.result())
SketchConstraintCoincidence_35.setName("SketchConstraintCoincidence_127")
SketchConstraintRadius_3 = Sketch_1.setRadius(SketchArc_3.results()[1], "BaseLegFillet")
SketchConstraintRadius_3.setName("SketchConstraintRadius_17")
SketchConstraintCoincidence_36 = Sketch_1.setCoincident(SketchLine_24.startPoint(), SketchLine_23.endPoint())
SketchConstraintCoincidence_36.setName("SketchConstraintCoincidence_128")
SketchArc_4 = Sketch_1.addArc(-27.44713036950059, 9, -27.44713039880284, 6, -24.49270712488033, 8.479055385239919, False)
SketchArc_4.setName("SketchArc_13")
SketchArc_4.result().setName("SketchArc_13")
SketchArc_4.results()[1].setName("SketchArc_13_2")
SketchConstraintCoincidence_37 = Sketch_1.setCoincident(SketchArc_4.startPoint(), SketchLine_11.startPoint())
SketchConstraintCoincidence_37.setName("SketchConstraintCoincidence_129")
SketchConstraintCoincidence_38 = Sketch_1.setCoincident(SketchArc_4.endPoint(), SketchLine_10.endPoint())
SketchConstraintCoincidence_38.setName("SketchConstraintCoincidence_130")
SketchConstraintTangent_7 = Sketch_1.setTangent(SketchArc_4.results()[1], SketchLine_10.result())
SketchConstraintTangent_7.setName("SketchConstraintTangent_23")
SketchConstraintTangent_8 = Sketch_1.setTangent(SketchArc_4.results()[1], SketchLine_11.result())
SketchConstraintTangent_8.setName("SketchConstraintTangent_24")
SketchConstraintCoincidence_39 = Sketch_1.setCoincident(SketchLine_23.startPoint(), SketchLine_10.startPoint())
SketchConstraintCoincidence_39.setName("SketchConstraintCoincidence_131")
SketchConstraintCoincidence_40 = Sketch_1.setCoincident(SketchLine_24.endPoint(), SketchLine_11.endPoint())
SketchConstraintCoincidence_40.setName("SketchConstraintCoincidence_132")
SketchConstraintCoincidence_41 = Sketch_1.setCoincident(SketchLine_10.endPoint(), SketchLine_23.result())
SketchConstraintCoincidence_41.setName("SketchConstraintCoincidence_133")
SketchConstraintCoincidence_42 = Sketch_1.setCoincident(SketchLine_11.startPoint(), SketchLine_24.result())
SketchConstraintCoincidence_42.setName("SketchConstraintCoincidence_134")
SketchConstraintRadius_4 = Sketch_1.setRadius(SketchArc_4.results()[1], "BaseLegFillet")
SketchConstraintRadius_4.setName("SketchConstraintRadius_18")
SketchConstraintCoincidence_43 = Sketch_1.setCoincident(SketchLine_21.startPoint(), SketchLine_12.startPoint())
SketchConstraintCoincidence_43.setName("SketchConstraintCoincidence_135")
SketchConstraintDistance_10 = Sketch_1.setDistance(SketchArc_4.endPoint(), SketchLine_18.result(), "LegThick")
SketchConstraintDistance_10.setName("SketchConstraintDistance_34")
model.do()
Sketch_2 = model.addSketch(Part_1_doc, model.defaultPlane("XOZ"))
SketchLine_25 = Sketch_2.addLine(-20, -5, -20, 37.99999996287101)
SketchLine_25.setName("SketchLine_73")
SketchLine_25.result().setName("SketchLine_73")
SketchLine_26 = Sketch_2.addLine(20, -5, -20, -5)
SketchLine_26.setName("SketchLine_18")
SketchLine_26.result().setName("SketchLine_18")
SketchLine_27 = Sketch_2.addLine(-18.00000018312083, 40, 18.00001539129446, 40)
SketchLine_27.setName("SketchLine_76")
SketchLine_27.result().setName("SketchLine_76")
SketchLine_28 = Sketch_2.addLine(20, 38.00000240162298, 20, -5)
SketchLine_28.setName("SketchLine_75")
SketchLine_28.result().setName("SketchLine_75")
SketchLine_29 = Sketch_2.addLine(20, 40, 20, -5)
SketchLine_29.setName("SketchLine_21")
SketchLine_29.result().setName("SketchLine_21")
SketchLine_29.setAuxiliary(True)
SketchConstraintCoincidence_44 = Sketch_2.setCoincident(SketchLine_29.endPoint(), SketchLine_26.startPoint())
SketchConstraintCoincidence_44.setName("SketchConstraintCoincidence_14")
SketchLine_30 = Sketch_2.addLine(-20, -5, -20, 40)
SketchLine_30.setName("SketchLine_19")
SketchLine_30.result().setName("SketchLine_19")
SketchLine_30.setAuxiliary(True)
SketchConstraintCoincidence_45 = Sketch_2.setCoincident(SketchLine_26.endPoint(), SketchLine_30.startPoint())
SketchConstraintCoincidence_45.setName("SketchConstraintCoincidence_15")
SketchLine_31 = Sketch_2.addLine(-20, 40, 20, 40)
SketchLine_31.setName("SketchLine_20")
SketchLine_31.result().setName("SketchLine_20")
SketchLine_31.setAuxiliary(True)
SketchConstraintCoincidence_46 = Sketch_2.setCoincident(SketchLine_30.endPoint(), SketchLine_31.startPoint())
SketchConstraintCoincidence_46.setName("SketchConstraintCoincidence_16")
SketchConstraintCoincidence_47 = Sketch_2.setCoincident(SketchLine_31.endPoint(), SketchLine_29.startPoint())
SketchConstraintCoincidence_47.setName("SketchConstraintCoincidence_17")
SketchConstraintHorizontal_8 = Sketch_2.setHorizontal(SketchLine_26.result())
SketchConstraintHorizontal_8.setName("SketchConstraintHorizontal_4")
SketchConstraintVertical_3 = Sketch_2.setVertical(SketchLine_30.result())
SketchConstraintVertical_3.setName("SketchConstraintVertical_2")
SketchConstraintHorizontal_9 = Sketch_2.setHorizontal(SketchLine_31.result())
SketchConstraintHorizontal_9.setName("SketchConstraintHorizontal_5")
SketchConstraintVertical_4 = Sketch_2.setVertical(SketchLine_29.result())
SketchConstraintVertical_4.setName("SketchConstraintVertical_3")
SketchLine_32 = Sketch_2.addLine(model.selection("EDGE", "PartSet/OZ"))
SketchLine_32.setName("SketchLine_22")
SketchLine_32.result().setName("SketchLine_22")
SketchConstraintDistance_11 = Sketch_2.setDistance(SketchLine_26.startPoint(), SketchLine_32.result(), "(TL/2-3)-20")
SketchConstraintDistance_11.setName("SketchConstraintDistance_5")
SketchConstraintDistance_12 = Sketch_2.setDistance(SketchLine_26.endPoint(), SketchLine_32.result(), "(TL/2-3)-20")
SketchConstraintDistance_12.setName("SketchConstraintDistance_6")
SketchLine_33 = Sketch_2.addLine(model.selection("EDGE", "PartSet/OX"))
SketchLine_33.setName("SketchLine_23")
SketchLine_33.result().setName("SketchLine_23")
SketchConstraintDistance_13 = Sketch_2.setDistance(SketchLine_29.startPoint(), SketchLine_33.result(), 40)
SketchConstraintDistance_13.setName("SketchConstraintDistance_7")
SketchConstraintDistance_14 = Sketch_2.setDistance(SketchLine_26.startPoint(), SketchLine_33.result(), 5)
SketchConstraintDistance_14.setName("SketchConstraintDistance_8")
SketchArc_5 = Sketch_2.addArc(-18, 37.99999999999999, -18.00000018312083, 40, -20, 37.99999996287101, False)
SketchArc_5.setName("SketchArc_10")
SketchArc_5.result().setName("SketchArc_10")
SketchArc_5.results()[1].setName("SketchArc_10_2")
SketchLine_34 = Sketch_2.addLine(-18.00000018312083, 40, 20, 40)
SketchLine_34.setName("SketchLine_74")
SketchLine_34.result().setName("SketchLine_74")
SketchLine_34.setAuxiliary(True)
SketchConstraintCoincidence_48 = Sketch_2.setCoincident(SketchArc_5.startPoint(), SketchLine_34.startPoint())
SketchConstraintCoincidence_48.setName("SketchConstraintCoincidence_101")
SketchConstraintCoincidence_49 = Sketch_2.setCoincident(SketchArc_5.endPoint(), SketchLine_25.endPoint())
SketchConstraintCoincidence_49.setName("SketchConstraintCoincidence_102")
SketchConstraintTangent_9 = Sketch_2.setTangent(SketchArc_5.results()[1], SketchLine_25.result())
SketchConstraintTangent_9.setName("SketchConstraintTangent_15")
SketchConstraintTangent_10 = Sketch_2.setTangent(SketchArc_5.results()[1], SketchLine_34.result())
SketchConstraintTangent_10.setName("SketchConstraintTangent_16")
SketchConstraintCoincidence_50 = Sketch_2.setCoincident(SketchLine_30.startPoint(), SketchLine_25.startPoint())
SketchConstraintCoincidence_50.setName("SketchConstraintCoincidence_103")
SketchConstraintCoincidence_51 = Sketch_2.setCoincident(SketchLine_31.endPoint(), SketchLine_34.endPoint())
SketchConstraintCoincidence_51.setName("SketchConstraintCoincidence_104")
SketchConstraintCoincidence_52 = Sketch_2.setCoincident(SketchLine_25.endPoint(), SketchLine_30.result())
SketchConstraintCoincidence_52.setName("SketchConstraintCoincidence_105")
SketchConstraintCoincidence_53 = Sketch_2.setCoincident(SketchLine_34.startPoint(), SketchLine_31.result())
SketchConstraintCoincidence_53.setName("SketchConstraintCoincidence_106")
SketchConstraintRadius_5 = Sketch_2.setRadius(SketchArc_5.results()[1], "BottomCutFillet")
SketchConstraintRadius_5.setName("SketchConstraintRadius_12")
SketchArc_6 = Sketch_2.addArc(18, 38.00000000000001, 20, 38.00000240162298, 18.00001539129446, 40, False)
SketchArc_6.setName("SketchArc_11")
SketchArc_6.result().setName("SketchArc_11")
SketchArc_6.results()[1].setName("SketchArc_11_2")
SketchConstraintCoincidence_54 = Sketch_2.setCoincident(SketchArc_6.startPoint(), SketchLine_28.startPoint())
SketchConstraintCoincidence_54.setName("SketchConstraintCoincidence_107")
SketchConstraintCoincidence_55 = Sketch_2.setCoincident(SketchArc_6.endPoint(), SketchLine_27.endPoint())
SketchConstraintCoincidence_55.setName("SketchConstraintCoincidence_108")
SketchConstraintTangent_11 = Sketch_2.setTangent(SketchArc_6.results()[1], SketchLine_28.result())
SketchConstraintTangent_11.setName("SketchConstraintTangent_17")
SketchConstraintTangent_12 = Sketch_2.setTangent(SketchArc_6.results()[1], SketchLine_27.result())
SketchConstraintTangent_12.setName("SketchConstraintTangent_18")
SketchConstraintCoincidence_56 = Sketch_2.setCoincident(SketchLine_29.endPoint(), SketchLine_28.endPoint())
SketchConstraintCoincidence_56.setName("SketchConstraintCoincidence_109")
SketchConstraintCoincidence_57 = Sketch_2.setCoincident(SketchLine_34.startPoint(), SketchLine_27.startPoint())
SketchConstraintCoincidence_57.setName("SketchConstraintCoincidence_110")
SketchConstraintCoincidence_58 = Sketch_2.setCoincident(SketchLine_28.startPoint(), SketchLine_29.result())
SketchConstraintCoincidence_58.setName("SketchConstraintCoincidence_111")
SketchConstraintCoincidence_59 = Sketch_2.setCoincident(SketchLine_27.endPoint(), SketchLine_34.result())
SketchConstraintCoincidence_59.setName("SketchConstraintCoincidence_112")
SketchConstraintRadius_6 = Sketch_2.setRadius(SketchArc_6.results()[1], "BottomCutFillet")
SketchConstraintRadius_6.setName("SketchConstraintRadius_13")
model.do()
Sketch_3 = model.addSketch(Part_1_doc, model.defaultPlane("YOZ"))
SketchCircle_1 = Sketch_3.addCircle(0, 85, 11)
SketchConstraintRadius_7 = Sketch_3.setRadius(SketchCircle_1.results()[1], "TDE/2")
SketchConstraintRadius_7.setName("SketchConstraintRadius_1")
SketchCircle_2 = Sketch_3.addCircle(0, 55, 11)
SketchLine_35 = Sketch_3.addLine(model.selection("EDGE", "PartSet/OZ"))
SketchLine_35.setName("SketchLine_24")
SketchLine_35.result().setName("SketchLine_24")
SketchConstraintCoincidence_60 = Sketch_3.setCoincident(SketchCircle_2.center(), SketchLine_35.result())
SketchConstraintCoincidence_60.setName("SketchConstraintCoincidence_18")
SketchConstraintRadius_8 = Sketch_3.setRadius(SketchCircle_2.results()[1], "TDE/2")
SketchConstraintRadius_8.setName("SketchConstraintRadius_2")
SketchConstraintDistance_15 = Sketch_3.setDistance(SketchCircle_2.center(), SketchCircle_1.center(), 30)
SketchConstraintDistance_15.setName("SketchConstraintDistance_9")
SketchLine_36 = Sketch_3.addLine(model.selection("EDGE", "Sketch_1/SketchLine_1"))
SketchLine_36.setName("SketchLine_25")
SketchLine_36.result().setName("SketchLine_25")
SketchConstraintDistance_16 = Sketch_3.setDistance(SketchCircle_1.center(), SketchLine_36.result(), 85)
SketchConstraintDistance_16.setName("SketchConstraintDistance_10")
model.do()
Sketch_4 = model.addSketch(Part_1_doc, model.defaultPlane("YOZ"))
SketchCircle_3 = Sketch_4.addCircle(0, 85, 7)
SketchCircle_4 = Sketch_4.addCircle(0, 55, 7)
SketchPoint_1 = Sketch_4.addPoint(model.selection("VERTEX", "Sketch_3/SketchCircle_1_2__cc"))
SketchConstraintCoincidence_61 = Sketch_4.setCoincident(SketchPoint_1.coordinates(), SketchCircle_3.center())
SketchConstraintCoincidence_61.setName("SketchConstraintCoincidence_19")
SketchPoint_2 = Sketch_4.addPoint(model.selection("VERTEX", "Sketch_3/SketchCircle_2_2__cc"))
SketchConstraintCoincidence_62 = Sketch_4.setCoincident(SketchPoint_2.coordinates(), SketchCircle_4.center())
SketchConstraintCoincidence_62.setName("SketchConstraintCoincidence_20")
SketchConstraintRadius_9 = Sketch_4.setRadius(SketchCircle_3.results()[1], "TDI/2")
SketchConstraintRadius_9.setName("SketchConstraintRadius_3")
SketchConstraintRadius_10 = Sketch_4.setRadius(SketchCircle_4.results()[1], "TDI/2")
SketchConstraintRadius_10.setName("SketchConstraintRadius_4")
model.do()
Extrusion_1 = model.addExtrusion(Part_1_doc, [model.selection("COMPOUND", "Sketch_1")], model.selection(), "TL/2-3", "TL/2-3")
ExtrusionCut_1 = model.addExtrusionCut(Part_1_doc, [model.selection("COMPOUND", "Sketch_2")], model.selection(), 100, 100, [model.selection("SOLID", "Extrusion_1_1")])
ExtrusionFuse_1 = model.addExtrusionFuse(Part_1_doc, [model.selection("COMPOUND", "Sketch_3")], model.selection(), "TL/2", "TL/2", [model.selection("SOLID", "ExtrusionCut_1_1")])
ExtrusionCut_2 = model.addExtrusionCut(Part_1_doc, [model.selection("COMPOUND", "Sketch_4")], model.selection(), 60, 60, [model.selection("SOLID", "ExtrusionFuse_1_1")])
Sketch_5 = model.addSketch(Part_1_doc, model.defaultPlane("XOY"))
SketchCircle_5 = Sketch_5.addCircle(30, -41, 7.5)
SketchLine_37 = Sketch_5.addLine(model.selection("EDGE", "PartSet/OX"))
SketchLine_37.setName("SketchLine_26")
SketchLine_37.result().setName("SketchLine_26")
SketchConstraintDistance_17 = Sketch_5.setDistance(SketchCircle_5.center(), SketchLine_37.result(), 41)
SketchConstraintDistance_17.setName("SketchConstraintDistance_13")
SketchLine_38 = Sketch_5.addLine(model.selection("EDGE", "PartSet/OY"))
SketchLine_38.setName("SketchLine_27")
SketchLine_38.result().setName("SketchLine_27")
SketchConstraintDistance_18 = Sketch_5.setDistance(SketchCircle_5.center(), SketchLine_38.result(), 30)
SketchConstraintDistance_18.setName("SketchConstraintDistance_14")
SketchConstraintRadius_11 = Sketch_5.setRadius(SketchCircle_5.results()[1], 7.5)
SketchConstraintRadius_11.setName("SketchConstraintRadius_5")
SketchConstraintMirror_1 = Sketch_5.addMirror(SketchLine_37.result(), [SketchCircle_5.results()[1]])
SketchConstraintMirror_1.setName("SketchConstraintMirror_2")
[SketchCircle_6] = SketchConstraintMirror_1.mirrored()
SketchConstraintMirror_2 = Sketch_5.addMirror(SketchLine_38.result(), [SketchCircle_5.results()[1], SketchCircle_6.results()[1]])
SketchConstraintMirror_2.setName("SketchConstraintMirror_3")
[SketchCircle_7, SketchCircle_8] = SketchConstraintMirror_2.mirrored()
model.do()
Sketch_6 = model.addSketch(Part_1_doc, model.defaultPlane("XOY"))
SketchCircle_9 = Sketch_6.addCircle(30, -41, 4)
SketchPoint_3 = Sketch_6.addPoint(model.selection("VERTEX", "Sketch_5/SketchCircle_5_2__cc"))
SketchConstraintCoincidence_63 = Sketch_6.setCoincident(SketchPoint_3.coordinates(), SketchCircle_9.center())
SketchConstraintCoincidence_63.setName("SketchConstraintCoincidence_21")
SketchConstraintRadius_12 = Sketch_6.setRadius(SketchCircle_9.results()[1], "BHD/2")
SketchConstraintRadius_12.setName("SketchConstraintRadius_6")
SketchLine_39 = Sketch_6.addLine(model.selection("EDGE", "PartSet/OX"))
SketchLine_39.setName("SketchLine_28")
SketchLine_39.result().setName("SketchLine_28")
SketchConstraintMirror_3 = Sketch_6.addMirror(SketchLine_39.result(), [SketchCircle_9.results()[1]])
SketchConstraintMirror_3.setName("SketchConstraintMirror_4")
[SketchCircle_10] = SketchConstraintMirror_3.mirrored()
SketchLine_40 = Sketch_6.addLine(model.selection("EDGE", "PartSet/OY"))
SketchLine_40.setName("SketchLine_29")
SketchLine_40.result().setName("SketchLine_29")
SketchConstraintMirror_4 = Sketch_6.addMirror(SketchLine_40.result(), [SketchCircle_9.results()[1], SketchCircle_10.results()[1]])
SketchConstraintMirror_4.setName("SketchConstraintMirror_5")
[SketchCircle_11, SketchCircle_12] = SketchConstraintMirror_4.mirrored()
model.do()
Plane_4 = model.addPlane(Part_1_doc, model.selection("FACE", "PartSet/YOZ"), 30, False)
Sketch_7 = model.addSketch(Part_1_doc, model.selection("FACE", "Plane_1"))
SketchLine_41 = Sketch_7.addLine(-41, 0, -41, 8)
SketchPoint_4 = Sketch_7.addPoint(model.selection("VERTEX", "Sketch_5/SketchCircle_5_2__cc"))
SketchConstraintCoincidence_64 = Sketch_7.setCoincident(SketchLine_41.startPoint(), SketchPoint_4.result())
SketchConstraintCoincidence_64.setName("SketchConstraintCoincidence_34")
SketchLine_42 = Sketch_7.addLine(-41, 8, -34, 8)
SketchConstraintCoincidence_65 = Sketch_7.setCoincident(SketchLine_41.endPoint(), SketchLine_42.startPoint())
SketchConstraintCoincidence_65.setName("SketchConstraintCoincidence_35")
SketchLine_43 = Sketch_7.addLine(-34, 8, -34, 7.499984403541713)
SketchLine_43.setName("SketchLine_47")
SketchLine_43.result().setName("SketchLine_47")
SketchLine_44 = Sketch_7.addLine(-32.50001348840178, 5.999999999999995, -32, 6)
SketchLine_44.setName("SketchLine_48")
SketchLine_44.result().setName("SketchLine_48")
SketchLine_45 = Sketch_7.addLine(-34, 8, -34, 6)
SketchLine_45.setName("SketchLine_43")
SketchLine_45.result().setName("SketchLine_43")
SketchLine_45.setAuxiliary(True)
SketchConstraintCoincidence_66 = Sketch_7.setCoincident(SketchLine_42.endPoint(), SketchLine_45.startPoint())
SketchConstraintCoincidence_66.setName("SketchConstraintCoincidence_36")
SketchLine_46 = Sketch_7.addLine(-34, 6, -32, 6)
SketchLine_46.setName("SketchLine_44")
SketchLine_46.result().setName("SketchLine_44")
SketchLine_46.setAuxiliary(True)
SketchConstraintCoincidence_67 = Sketch_7.setCoincident(SketchLine_45.endPoint(), SketchLine_46.startPoint())
SketchConstraintCoincidence_67.setName("SketchConstraintCoincidence_37")
SketchLine_47 = Sketch_7.addLine(-32, 6, -32, 0)
SketchLine_47.setName("SketchLine_45")
SketchLine_47.result().setName("SketchLine_45")
SketchConstraintCoincidence_68 = Sketch_7.setCoincident(SketchLine_46.endPoint(), SketchLine_47.startPoint())
SketchConstraintCoincidence_68.setName("SketchConstraintCoincidence_38")
SketchLine_48 = Sketch_7.addLine(-32, 0, -41, 0)
SketchLine_48.setName("SketchLine_46")
SketchLine_48.result().setName("SketchLine_46")
SketchConstraintCoincidence_69 = Sketch_7.setCoincident(SketchLine_47.endPoint(), SketchLine_48.startPoint())
SketchConstraintCoincidence_69.setName("SketchConstraintCoincidence_39")
SketchConstraintCoincidence_70 = Sketch_7.setCoincident(SketchLine_41.startPoint(), SketchLine_48.endPoint())
SketchConstraintCoincidence_70.setName("SketchConstraintCoincidence_40")
SketchConstraintCoincidence_71 = Sketch_7.setCoincident(SketchPoint_4.coordinates(), SketchLine_48.endPoint())
SketchConstraintCoincidence_71.setName("SketchConstraintCoincidence_41")
SketchConstraintHorizontal_10 = Sketch_7.setHorizontal(SketchLine_48.result())
SketchConstraintHorizontal_10.setName("SketchConstraintHorizontal_6")
SketchConstraintVertical_5 = Sketch_7.setVertical(SketchLine_41.result())
SketchConstraintVertical_5.setName("SketchConstraintVertical_4")
SketchConstraintVertical_6 = Sketch_7.setVertical(SketchLine_47.result())
SketchConstraintVertical_6.setName("SketchConstraintVertical_5")
SketchConstraintHorizontal_11 = Sketch_7.setHorizontal(SketchLine_46.result())
SketchConstraintHorizontal_11.setName("SketchConstraintHorizontal_7")
SketchConstraintVertical_7 = Sketch_7.setVertical(SketchLine_45.result())
SketchConstraintVertical_7.setName("SketchConstraintVertical_6")
SketchConstraintHorizontal_12 = Sketch_7.setHorizontal(SketchLine_42.result())
SketchConstraintHorizontal_12.setName("SketchConstraintHorizontal_8")
SketchConstraintDistance_19 = Sketch_7.setDistance(SketchLine_41.endPoint(), SketchLine_48.result(), "BPS+BHPS")
SketchConstraintDistance_19.setName("SketchConstraintDistance_15")
SketchConstraintDistance_20 = Sketch_7.setDistance(SketchLine_47.startPoint(), SketchLine_48.result(), "BPS")
SketchConstraintDistance_20.setName("SketchConstraintDistance_16")
SketchConstraintDistance_21 = Sketch_7.setDistance(SketchLine_48.startPoint(), SketchLine_41.result(), "BHPD/2+BHPFR+0.5")
SketchConstraintDistance_21.setName("SketchConstraintDistance_17")
SketchConstraintDistance_22 = Sketch_7.setDistance(SketchLine_42.endPoint(), SketchLine_41.result(), "BHPD/2")
SketchConstraintDistance_22.setName("SketchConstraintDistance_18")
SketchArc_7 = Sketch_7.addArc(-32.50000000000004, 7.499999999999999, -34, 7.499984403541713, -32.50001348840178, 5.999999999999995, False)
SketchArc_7.setName("SketchArc_5")
SketchArc_7.result().setName("SketchArc_5")
SketchArc_7.results()[1].setName("SketchArc_5_2")
SketchConstraintCoincidence_72 = Sketch_7.setCoincident(SketchArc_7.startPoint(), SketchLine_43.endPoint())
SketchConstraintCoincidence_72.setName("SketchConstraintCoincidence_42")
SketchConstraintCoincidence_73 = Sketch_7.setCoincident(SketchArc_7.endPoint(), SketchLine_44.startPoint())
SketchConstraintCoincidence_73.setName("SketchConstraintCoincidence_43")
SketchConstraintTangent_13 = Sketch_7.setTangent(SketchArc_7.results()[1], SketchLine_43.result())
SketchConstraintTangent_13.setName("SketchConstraintTangent_5")
SketchConstraintTangent_14 = Sketch_7.setTangent(SketchArc_7.results()[1], SketchLine_44.result())
SketchConstraintTangent_14.setName("SketchConstraintTangent_6")
SketchConstraintCoincidence_74 = Sketch_7.setCoincident(SketchLine_45.startPoint(), SketchLine_43.startPoint())
SketchConstraintCoincidence_74.setName("SketchConstraintCoincidence_44")
SketchConstraintCoincidence_75 = Sketch_7.setCoincident(SketchLine_46.endPoint(), SketchLine_44.endPoint())
SketchConstraintCoincidence_75.setName("SketchConstraintCoincidence_45")
SketchConstraintCoincidence_76 = Sketch_7.setCoincident(SketchLine_43.endPoint(), SketchLine_45.result())
SketchConstraintCoincidence_76.setName("SketchConstraintCoincidence_46")
SketchConstraintCoincidence_77 = Sketch_7.setCoincident(SketchLine_44.startPoint(), SketchLine_46.result())
SketchConstraintCoincidence_77.setName("SketchConstraintCoincidence_47")
SketchConstraintRadius_13 = Sketch_7.setRadius(SketchArc_7.results()[1], "BHPFR")
SketchConstraintRadius_13.setName("SketchConstraintRadius_8")
model.do()
RevolutionFuse_1 = model.addRevolutionFuse(Part_1_doc, [model.selection("COMPOUND", "Sketch_7")], model.selection("EDGE", "Sketch_7/SketchLine_41"), 360, 0, [model.selection("SOLID", "ExtrusionCut_2_1")])
Sketch_8 = model.addSketch(Part_1_doc, model.selection("FACE", "Plane_1"))
SketchLine_49 = Sketch_8.addLine(32, 6, 32.50001476412091, 6.000000000000001)
SketchLine_49.setName("SketchLine_55")
SketchLine_49.result().setName("SketchLine_55")
SketchLine_50 = Sketch_8.addLine(32, 0, 41, 0)
SketchLine_50.setName("SketchLine_49")
SketchLine_50.result().setName("SketchLine_49")
SketchPoint_5 = Sketch_8.addPoint(model.selection("VERTEX", "Sketch_6/SketchCircle_10_2__cc"))
SketchConstraintCoincidence_78 = Sketch_8.setCoincident(SketchLine_50.endPoint(), SketchPoint_5.result())
SketchConstraintCoincidence_78.setName("SketchConstraintCoincidence_50")
SketchLine_51 = Sketch_8.addLine(41, 0, 41, 8)
SketchLine_51.setName("SketchLine_50")
SketchLine_51.result().setName("SketchLine_50")
SketchLine_52 = Sketch_8.addLine(34, 7.499985233923545, 34, 8)
SketchLine_52.setName("SketchLine_56")
SketchLine_52.result().setName("SketchLine_56")
SketchLine_53 = Sketch_8.addLine(32, 6, 32, 0)
SketchLine_53.setName("SketchLine_52")
SketchLine_53.result().setName("SketchLine_52")
SketchConstraintCoincidence_79 = Sketch_8.setCoincident(SketchLine_53.endPoint(), SketchLine_50.startPoint())
SketchConstraintCoincidence_79.setName("SketchConstraintCoincidence_51")
SketchConstraintCoincidence_80 = Sketch_8.setCoincident(SketchLine_50.endPoint(), SketchLine_51.startPoint())
SketchConstraintCoincidence_80.setName("SketchConstraintCoincidence_52")
SketchLine_54 = Sketch_8.addLine(41, 8, 34, 8)
SketchLine_54.setName("SketchLine_53")
SketchLine_54.result().setName("SketchLine_53")
SketchConstraintCoincidence_81 = Sketch_8.setCoincident(SketchLine_51.endPoint(), SketchLine_54.startPoint())
SketchConstraintCoincidence_81.setName("SketchConstraintCoincidence_53")
SketchConstraintHorizontal_13 = Sketch_8.setHorizontal(SketchLine_50.result())
SketchConstraintHorizontal_13.setName("SketchConstraintHorizontal_9")
SketchConstraintVertical_8 = Sketch_8.setVertical(SketchLine_51.result())
SketchConstraintVertical_8.setName("SketchConstraintVertical_7")
SketchConstraintVertical_9 = Sketch_8.setVertical(SketchLine_53.result())
SketchConstraintVertical_9.setName("SketchConstraintVertical_8")
SketchPoint_6 = Sketch_8.addPoint(32, 6)
SketchConstraintCoincidence_82 = Sketch_8.setCoincident(SketchPoint_6.coordinates(), SketchLine_53.startPoint())
SketchConstraintCoincidence_82.setName("SketchConstraintCoincidence_55")
SketchPoint_7 = Sketch_8.addPoint(34, 8)
SketchConstraintCoincidence_83 = Sketch_8.setCoincident(SketchLine_54.endPoint(), SketchPoint_7.coordinates())
SketchConstraintCoincidence_83.setName("SketchConstraintCoincidence_58")
SketchLine_55 = Sketch_8.addLine(32, 6, 34, 6)
SketchLine_55.setName("SketchLine_51")
SketchLine_55.result().setName("SketchLine_51")
SketchLine_55.setAuxiliary(True)
SketchConstraintCoincidence_84 = Sketch_8.setCoincident(SketchLine_53.startPoint(), SketchLine_55.startPoint())
SketchConstraintCoincidence_84.setName("SketchConstraintCoincidence_54")
SketchConstraintCoincidence_85 = Sketch_8.setCoincident(SketchPoint_6.coordinates(), SketchLine_55.startPoint())
SketchConstraintCoincidence_85.setName("SketchConstraintCoincidence_56")
SketchLine_56 = Sketch_8.addLine(34, 6, 34, 8)
SketchLine_56.setName("SketchLine_54")
SketchLine_56.result().setName("SketchLine_54")
SketchLine_56.setAuxiliary(True)
SketchConstraintCoincidence_86 = Sketch_8.setCoincident(SketchLine_55.endPoint(), SketchLine_56.startPoint())
SketchConstraintCoincidence_86.setName("SketchConstraintCoincidence_57")
SketchConstraintCoincidence_87 = Sketch_8.setCoincident(SketchPoint_7.coordinates(), SketchLine_56.endPoint())
SketchConstraintCoincidence_87.setName("SketchConstraintCoincidence_59")
SketchConstraintCoincidence_88 = Sketch_8.setCoincident(SketchLine_54.endPoint(), SketchLine_56.endPoint())
SketchConstraintCoincidence_88.setName("SketchConstraintCoincidence_60")
SketchConstraintHorizontal_14 = Sketch_8.setHorizontal(SketchLine_55.result())
SketchConstraintHorizontal_14.setName("SketchConstraintHorizontal_10")
SketchConstraintVertical_10 = Sketch_8.setVertical(SketchLine_56.result())
SketchConstraintVertical_10.setName("SketchConstraintVertical_9")
SketchConstraintDistance_23 = Sketch_8.setDistance(SketchPoint_7.coordinates(), SketchLine_50.result(), 8)
SketchConstraintDistance_23.setName("SketchConstraintDistance_19")
SketchConstraintHorizontal_15 = Sketch_8.setHorizontal(SketchLine_54.result())
SketchConstraintHorizontal_15.setName("SketchConstraintHorizontal_11")
SketchConstraintDistance_24 = Sketch_8.setDistance(SketchLine_53.startPoint(), SketchLine_51.result(), 9)
SketchConstraintDistance_24.setName("SketchConstraintDistance_20")
SketchConstraintDistance_25 = Sketch_8.setDistance(SketchPoint_7.coordinates(), SketchLine_51.result(), 7)
SketchConstraintDistance_25.setName("SketchConstraintDistance_21")
SketchConstraintDistance_26 = Sketch_8.setDistance(SketchLine_53.startPoint(), SketchLine_50.result(), 6)
SketchConstraintDistance_26.setName("SketchConstraintDistance_22")
SketchArc_8 = Sketch_8.addArc(32.50000000000001, 7.500000000000025, 32.50001476412091, 6.000000000000001, 34, 7.499985233923545, False)
SketchArc_8.setName("SketchArc_7")
SketchArc_8.result().setName("SketchArc_7")
SketchArc_8.results()[1].setName("SketchArc_7_2")
SketchConstraintCoincidence_89 = Sketch_8.setCoincident(SketchArc_8.startPoint(), SketchLine_49.endPoint())
SketchConstraintCoincidence_89.setName("SketchConstraintCoincidence_61")
SketchConstraintCoincidence_90 = Sketch_8.setCoincident(SketchArc_8.endPoint(), SketchLine_52.startPoint())
SketchConstraintCoincidence_90.setName("SketchConstraintCoincidence_62")
SketchConstraintTangent_15 = Sketch_8.setTangent(SketchArc_8.results()[1], SketchLine_49.result())
SketchConstraintTangent_15.setName("SketchConstraintTangent_9")
SketchConstraintTangent_16 = Sketch_8.setTangent(SketchArc_8.results()[1], SketchLine_52.result())
SketchConstraintTangent_16.setName("SketchConstraintTangent_10")
SketchConstraintCoincidence_91 = Sketch_8.setCoincident(SketchLine_55.startPoint(), SketchLine_49.startPoint())
SketchConstraintCoincidence_91.setName("SketchConstraintCoincidence_63")
SketchConstraintCoincidence_92 = Sketch_8.setCoincident(SketchLine_56.endPoint(), SketchLine_52.endPoint())
SketchConstraintCoincidence_92.setName("SketchConstraintCoincidence_64")
SketchConstraintCoincidence_93 = Sketch_8.setCoincident(SketchLine_49.endPoint(), SketchLine_55.result())
SketchConstraintCoincidence_93.setName("SketchConstraintCoincidence_65")
SketchConstraintCoincidence_94 = Sketch_8.setCoincident(SketchLine_52.startPoint(), SketchLine_56.result())
SketchConstraintCoincidence_94.setName("SketchConstraintCoincidence_66")
SketchConstraintRadius_14 = Sketch_8.setRadius(SketchArc_8.results()[1], 1.5)
SketchConstraintRadius_14.setName("SketchConstraintRadius_9")
model.do()
RevolutionFuse_2 = model.addRevolutionFuse(Part_1_doc, [model.selection("FACE", "Sketch_8/Face-SketchLine_52f-SketchLine_49f-SketchLine_50f-SketchLine_53f-SketchLine_56r-SketchArc_7_2r-SketchLine_55r")], model.selection("EDGE", "Sketch_8/SketchLine_50"), 360, 0, [model.selection("SOLID", "RevolutionFuse_1_1")])
Plane_5 = model.addPlane(Part_1_doc, model.selection("FACE", "PartSet/YOZ"), 30, True)
Sketch_9 = model.addSketch(Part_1_doc, model.selection("FACE", "Plane_2"))
SketchLine_57 = Sketch_9.addLine(-32.50001494742042, 5.999999999999998, -32, 6)
SketchLine_57.setName("SketchLine_63")
SketchLine_57.result().setName("SketchLine_63")
SketchLine_58 = Sketch_9.addLine(-32, 0, -41, 0)
SketchLine_58.setName("SketchLine_57")
SketchLine_58.result().setName("SketchLine_57")
SketchPoint_8 = Sketch_9.addPoint(model.selection("VERTEX", "Sketch_6/SketchCircle_11_2__cc"))
SketchConstraintCoincidence_95 = Sketch_9.setCoincident(SketchLine_58.endPoint(), SketchPoint_8.result())
SketchConstraintCoincidence_95.setName("SketchConstraintCoincidence_67")
SketchLine_59 = Sketch_9.addLine(-41, 0, -41, 7.999999999999999)
SketchLine_59.setName("SketchLine_58")
SketchLine_59.result().setName("SketchLine_58")
SketchLine_60 = Sketch_9.addLine(-41, 7.999999999999999, -34, 8)
SketchLine_60.setName("SketchLine_59")
SketchLine_60.result().setName("SketchLine_59")
SketchLine_61 = Sketch_9.addLine(-32, 6, -32, 0)
SketchLine_61.setName("SketchLine_60")
SketchLine_61.result().setName("SketchLine_60")
SketchConstraintCoincidence_96 = Sketch_9.setCoincident(SketchLine_61.endPoint(), SketchLine_58.startPoint())
SketchConstraintCoincidence_96.setName("SketchConstraintCoincidence_68")
SketchConstraintCoincidence_97 = Sketch_9.setCoincident(SketchLine_58.endPoint(), SketchLine_59.startPoint())
SketchConstraintCoincidence_97.setName("SketchConstraintCoincidence_69")
SketchConstraintCoincidence_98 = Sketch_9.setCoincident(SketchLine_59.endPoint(), SketchLine_60.startPoint())
SketchConstraintCoincidence_98.setName("SketchConstraintCoincidence_70")
SketchLine_62 = Sketch_9.addLine(-34, 8, -33.99999999999999, 7.499985052178464)
SketchLine_62.setName("SketchLine_64")
SketchLine_62.result().setName("SketchLine_64")
SketchConstraintHorizontal_16 = Sketch_9.setHorizontal(SketchLine_58.result())
SketchConstraintHorizontal_16.setName("SketchConstraintHorizontal_12")
SketchConstraintVertical_11 = Sketch_9.setVertical(SketchLine_59.result())
SketchConstraintVertical_11.setName("SketchConstraintVertical_10")
SketchConstraintHorizontal_17 = Sketch_9.setHorizontal(SketchLine_60.result())
SketchConstraintHorizontal_17.setName("SketchConstraintHorizontal_13")
SketchConstraintVertical_12 = Sketch_9.setVertical(SketchLine_61.result())
SketchConstraintVertical_12.setName("SketchConstraintVertical_11")
SketchPoint_9 = Sketch_9.addPoint(-34, 8)
SketchConstraintCoincidence_99 = Sketch_9.setCoincident(SketchPoint_9.coordinates(), SketchLine_60.endPoint())
SketchConstraintCoincidence_99.setName("SketchConstraintCoincidence_72")
SketchPoint_10 = Sketch_9.addPoint(-32, 6)
SketchConstraintCoincidence_100 = Sketch_9.setCoincident(SketchPoint_10.coordinates(), SketchLine_61.startPoint())
SketchConstraintCoincidence_100.setName("SketchConstraintCoincidence_73")
SketchLine_63 = Sketch_9.addLine(-34, 8, -34, 6)
SketchLine_63.setName("SketchLine_61")
SketchLine_63.result().setName("SketchLine_61")
SketchLine_63.setAuxiliary(True)
SketchConstraintCoincidence_101 = Sketch_9.setCoincident(SketchLine_60.endPoint(), SketchLine_63.startPoint())
SketchConstraintCoincidence_101.setName("SketchConstraintCoincidence_71")
SketchConstraintCoincidence_102 = Sketch_9.setCoincident(SketchPoint_9.coordinates(), SketchLine_63.startPoint())
SketchConstraintCoincidence_102.setName("SketchConstraintCoincidence_74")
SketchLine_64 = Sketch_9.addLine(-34, 6, -32, 6)
SketchLine_64.setName("SketchLine_62")
SketchLine_64.result().setName("SketchLine_62")
SketchLine_64.setAuxiliary(True)
SketchConstraintCoincidence_103 = Sketch_9.setCoincident(SketchLine_63.endPoint(), SketchLine_64.startPoint())
SketchConstraintCoincidence_103.setName("SketchConstraintCoincidence_75")
SketchConstraintCoincidence_104 = Sketch_9.setCoincident(SketchLine_61.startPoint(), SketchLine_64.endPoint())
SketchConstraintCoincidence_104.setName("SketchConstraintCoincidence_76")
SketchConstraintCoincidence_105 = Sketch_9.setCoincident(SketchPoint_10.coordinates(), SketchLine_64.endPoint())
SketchConstraintCoincidence_105.setName("SketchConstraintCoincidence_77")
SketchConstraintHorizontal_18 = Sketch_9.setHorizontal(SketchLine_64.result())
SketchConstraintHorizontal_18.setName("SketchConstraintHorizontal_14")
SketchConstraintVertical_13 = Sketch_9.setVertical(SketchLine_63.result())
SketchConstraintVertical_13.setName("SketchConstraintVertical_12")
SketchConstraintDistance_27 = Sketch_9.setDistance(SketchLine_61.startPoint(), SketchLine_58.result(), 6)
SketchConstraintDistance_27.setName("SketchConstraintDistance_23")
SketchConstraintDistance_28 = Sketch_9.setDistance(SketchLine_60.endPoint(), SketchLine_58.result(), 8)
SketchConstraintDistance_28.setName("SketchConstraintDistance_24")
SketchConstraintDistance_29 = Sketch_9.setDistance(SketchLine_60.endPoint(), SketchLine_59.result(), 7)
SketchConstraintDistance_29.setName("SketchConstraintDistance_25")
SketchConstraintDistance_30 = Sketch_9.setDistance(SketchLine_61.startPoint(), SketchLine_63.result(), 2)
SketchConstraintDistance_30.setName("SketchConstraintDistance_26")
SketchArc_9 = Sketch_9.addArc(-32.49999999999999, 7.499999999999997, -33.99999999999999, 7.499985052178464, -32.50001494742042, 5.999999999999998, False)
SketchArc_9.setName("SketchArc_8")
SketchArc_9.result().setName("SketchArc_8")
SketchArc_9.results()[1].setName("SketchArc_8_2")
SketchConstraintCoincidence_106 = Sketch_9.setCoincident(SketchArc_9.startPoint(), SketchLine_62.endPoint())
SketchConstraintCoincidence_106.setName("SketchConstraintCoincidence_78")
SketchConstraintCoincidence_107 = Sketch_9.setCoincident(SketchArc_9.endPoint(), SketchLine_57.startPoint())
SketchConstraintCoincidence_107.setName("SketchConstraintCoincidence_79")
SketchConstraintTangent_17 = Sketch_9.setTangent(SketchArc_9.results()[1], SketchLine_57.result())
SketchConstraintTangent_17.setName("SketchConstraintTangent_11")
SketchConstraintTangent_18 = Sketch_9.setTangent(SketchArc_9.results()[1], SketchLine_62.result())
SketchConstraintTangent_18.setName("SketchConstraintTangent_12")
SketchConstraintCoincidence_108 = Sketch_9.setCoincident(SketchLine_64.endPoint(), SketchLine_57.endPoint())
SketchConstraintCoincidence_108.setName("SketchConstraintCoincidence_80")
SketchConstraintCoincidence_109 = Sketch_9.setCoincident(SketchLine_63.startPoint(), SketchLine_62.startPoint())
SketchConstraintCoincidence_109.setName("SketchConstraintCoincidence_81")
SketchConstraintCoincidence_110 = Sketch_9.setCoincident(SketchLine_57.startPoint(), SketchLine_64.result())
SketchConstraintCoincidence_110.setName("SketchConstraintCoincidence_82")
SketchConstraintCoincidence_111 = Sketch_9.setCoincident(SketchLine_62.endPoint(), SketchLine_63.result())
SketchConstraintCoincidence_111.setName("SketchConstraintCoincidence_83")
SketchConstraintRadius_15 = Sketch_9.setRadius(SketchArc_9.results()[1], 1.5)
SketchConstraintRadius_15.setName("SketchConstraintRadius_10")
model.do()
Sketch_10 = model.addSketch(Part_1_doc, model.selection("FACE", "Plane_2"))
SketchLine_65 = Sketch_10.addLine(33.99999999999999, 7.999999999999999, 33.99999999999999, 7.499985050625134)
SketchLine_65.setName("SketchLine_71")
SketchLine_65.result().setName("SketchLine_71")
SketchLine_66 = Sketch_10.addLine(32, 0, 41, 0)
SketchLine_66.setName("SketchLine_65")
SketchLine_66.result().setName("SketchLine_65")
SketchPoint_11 = Sketch_10.addPoint(model.selection("VERTEX", "Sketch_6/SketchCircle_12_2__cc"))
SketchConstraintCoincidence_112 = Sketch_10.setCoincident(SketchLine_66.endPoint(), SketchPoint_11.result())
SketchConstraintCoincidence_112.setName("SketchConstraintCoincidence_84")
SketchLine_67 = Sketch_10.addLine(41, 0, 41, 7.999999999999999)
SketchLine_67.setName("SketchLine_66")
SketchLine_67.result().setName("SketchLine_66")
SketchLine_68 = Sketch_10.addLine(41, 7.999999999999999, 33.99999999999999, 7.999999999999999)
SketchLine_68.setName("SketchLine_67")
SketchLine_68.result().setName("SketchLine_67")
SketchLine_69 = Sketch_10.addLine(32, 6, 32, 0)
SketchLine_69.setName("SketchLine_68")
SketchLine_69.result().setName("SketchLine_68")
SketchConstraintCoincidence_113 = Sketch_10.setCoincident(SketchLine_69.endPoint(), SketchLine_66.startPoint())
SketchConstraintCoincidence_113.setName("SketchConstraintCoincidence_85")
SketchConstraintCoincidence_114 = Sketch_10.setCoincident(SketchLine_66.endPoint(), SketchLine_67.startPoint())
SketchConstraintCoincidence_114.setName("SketchConstraintCoincidence_86")
SketchConstraintCoincidence_115 = Sketch_10.setCoincident(SketchLine_67.endPoint(), SketchLine_68.startPoint())
SketchConstraintCoincidence_115.setName("SketchConstraintCoincidence_87")
SketchLine_70 = Sketch_10.addLine(32.50001494562209, 6.000000000000006, 32, 6)
SketchLine_70.setName("SketchLine_72")
SketchLine_70.result().setName("SketchLine_72")
SketchConstraintHorizontal_19 = Sketch_10.setHorizontal(SketchLine_66.result())
SketchConstraintHorizontal_19.setName("SketchConstraintHorizontal_15")
SketchConstraintVertical_14 = Sketch_10.setVertical(SketchLine_67.result())
SketchConstraintVertical_14.setName("SketchConstraintVertical_13")
SketchConstraintHorizontal_20 = Sketch_10.setHorizontal(SketchLine_68.result())
SketchConstraintHorizontal_20.setName("SketchConstraintHorizontal_16")
SketchConstraintVertical_15 = Sketch_10.setVertical(SketchLine_69.result())
SketchConstraintVertical_15.setName("SketchConstraintVertical_14")
SketchPoint_12 = Sketch_10.addPoint(33.99999999999999, 7.999999999999999)
SketchConstraintCoincidence_116 = Sketch_10.setCoincident(SketchPoint_12.coordinates(), SketchLine_68.endPoint())
SketchConstraintCoincidence_116.setName("SketchConstraintCoincidence_89")
SketchPoint_13 = Sketch_10.addPoint(32, 6)
SketchConstraintCoincidence_117 = Sketch_10.setCoincident(SketchPoint_13.coordinates(), SketchLine_69.startPoint())
SketchConstraintCoincidence_117.setName("SketchConstraintCoincidence_90")
SketchLine_71 = Sketch_10.addLine(33.99999999999999, 7.999999999999999, 34, 6)
SketchLine_71.setName("SketchLine_69")
SketchLine_71.result().setName("SketchLine_69")
SketchLine_71.setAuxiliary(True)
SketchConstraintCoincidence_118 = Sketch_10.setCoincident(SketchLine_68.endPoint(), SketchLine_71.startPoint())
SketchConstraintCoincidence_118.setName("SketchConstraintCoincidence_88")
SketchConstraintCoincidence_119 = Sketch_10.setCoincident(SketchPoint_12.coordinates(), SketchLine_71.startPoint())
SketchConstraintCoincidence_119.setName("SketchConstraintCoincidence_91")
SketchLine_72 = Sketch_10.addLine(34, 6, 32, 6)
SketchLine_72.setName("SketchLine_70")
SketchLine_72.result().setName("SketchLine_70")
SketchLine_72.setAuxiliary(True)
SketchConstraintCoincidence_120 = Sketch_10.setCoincident(SketchLine_71.endPoint(), SketchLine_72.startPoint())
SketchConstraintCoincidence_120.setName("SketchConstraintCoincidence_92")
SketchConstraintCoincidence_121 = Sketch_10.setCoincident(SketchLine_69.startPoint(), SketchLine_72.endPoint())
SketchConstraintCoincidence_121.setName("SketchConstraintCoincidence_93")
SketchConstraintCoincidence_122 = Sketch_10.setCoincident(SketchPoint_13.coordinates(), SketchLine_72.endPoint())
SketchConstraintCoincidence_122.setName("SketchConstraintCoincidence_94")
SketchConstraintHorizontal_21 = Sketch_10.setHorizontal(SketchLine_72.result())
SketchConstraintHorizontal_21.setName("SketchConstraintHorizontal_17")
SketchConstraintVertical_16 = Sketch_10.setVertical(SketchLine_71.result())
SketchConstraintVertical_16.setName("SketchConstraintVertical_15")
SketchConstraintDistance_31 = Sketch_10.setDistance(SketchLine_71.startPoint(), SketchLine_67.result(), 7)
SketchConstraintDistance_31.setName("SketchConstraintDistance_27")
SketchConstraintDistance_32 = Sketch_10.setDistance(SketchLine_69.startPoint(), SketchLine_71.result(), 2)
SketchConstraintDistance_32.setName("SketchConstraintDistance_28")
SketchConstraintDistance_33 = Sketch_10.setDistance(SketchLine_69.startPoint(), SketchLine_66.result(), 6)
SketchConstraintDistance_33.setName("SketchConstraintDistance_29")
SketchConstraintDistance_34 = Sketch_10.setDistance(SketchLine_71.startPoint(), SketchLine_66.result(), 8)
SketchConstraintDistance_34.setName("SketchConstraintDistance_30")
SketchArc_10 = Sketch_10.addArc(32.50000000000002, 7.500000000000033, 32.50001494562209, 6.000000000000006, 33.99999999999999, 7.499985050625134, False)
SketchArc_10.setName("SketchArc_9")
SketchArc_10.result().setName("SketchArc_9")
SketchArc_10.results()[1].setName("SketchArc_9_2")
SketchConstraintCoincidence_123 = Sketch_10.setCoincident(SketchArc_10.startPoint(), SketchLine_70.startPoint())
SketchConstraintCoincidence_123.setName("SketchConstraintCoincidence_95")
SketchConstraintCoincidence_124 = Sketch_10.setCoincident(SketchArc_10.endPoint(), SketchLine_65.endPoint())
SketchConstraintCoincidence_124.setName("SketchConstraintCoincidence_96")
SketchConstraintTangent_19 = Sketch_10.setTangent(SketchArc_10.results()[1], SketchLine_65.result())
SketchConstraintTangent_19.setName("SketchConstraintTangent_13")
SketchConstraintTangent_20 = Sketch_10.setTangent(SketchArc_10.results()[1], SketchLine_70.result())
SketchConstraintTangent_20.setName("SketchConstraintTangent_14")
SketchConstraintCoincidence_125 = Sketch_10.setCoincident(SketchLine_71.startPoint(), SketchLine_65.startPoint())
SketchConstraintCoincidence_125.setName("SketchConstraintCoincidence_97")
SketchConstraintCoincidence_126 = Sketch_10.setCoincident(SketchLine_72.endPoint(), SketchLine_70.endPoint())
SketchConstraintCoincidence_126.setName("SketchConstraintCoincidence_98")
SketchConstraintCoincidence_127 = Sketch_10.setCoincident(SketchLine_65.endPoint(), SketchLine_71.result())
SketchConstraintCoincidence_127.setName("SketchConstraintCoincidence_99")
SketchConstraintCoincidence_128 = Sketch_10.setCoincident(SketchLine_70.startPoint(), SketchLine_72.result())
SketchConstraintCoincidence_128.setName("SketchConstraintCoincidence_100")
SketchConstraintRadius_16 = Sketch_10.setRadius(SketchArc_10.results()[1], 1.5)
SketchConstraintRadius_16.setName("SketchConstraintRadius_11")
model.do()
RevolutionFuse_3 = model.addRevolutionFuse(Part_1_doc, [model.selection("COMPOUND", "Sketch_9")], model.selection("EDGE", "Sketch_9/SketchLine_58"), 360, 0, [model.selection("SOLID", "RevolutionFuse_2_1")])
RevolutionFuse_4 = model.addRevolutionFuse(Part_1_doc, [model.selection("COMPOUND", "Sketch_10")], model.selection("EDGE", "Sketch_10/SketchLine_66"), 360, 0, [model.selection("SOLID", "RevolutionFuse_3_1")])
ExtrusionCut_3 = model.addExtrusionCut(Part_1_doc, [model.selection("FACE", "Sketch_6/Face-SketchCircle_11_2f"), model.selection("FACE", "Sketch_6/Face-SketchCircle_9_2r"), model.selection("WIRE", "Sketch_6/Face-SketchCircle_10_2f_wire"), model.selection("FACE", "Sketch_6/Face-SketchCircle_12_2f")], model.selection("EDGE", "PartSet/OZ"), "BPS+5", 5, [model.selection("SOLID", "RevolutionFuse_4_1")])

# Test reexecution after parameter change
Parameter_BPS.setValue(3)
model.do()
model.testResultsVolumes(ExtrusionCut_3, [154096.039414040715200826525688171])
Parameter_BPS.setValue(6)
model.end()

from GeomAPI import GeomAPI_Shape

model.testNbResults(ExtrusionCut_3, 1)
model.testNbSubShapes(ExtrusionCut_3, GeomAPI_Shape.SOLID, [1])
