import model

model.begin()
partSet = model.moduleDocument()
Part_1 = model.addPart(partSet)
Part_1_doc = Part_1.document()
Sketch_1 = model.addSketch(Part_1_doc, model.defaultPlane("XOY"))
SketchLine_1 = Sketch_1.addLine(0, 0, 0, 50)
SketchLine_2 = Sketch_1.addLine(0, 50, 50, 50)
SketchConstraintCoincidence_1 = Sketch_1.setCoincident(SketchLine_1.endPoint(), SketchLine_2.startPoint())
SketchLine_3 = Sketch_1.addLine(50, 50, 50, 0)
SketchConstraintCoincidence_2 = Sketch_1.setCoincident(SketchLine_2.endPoint(), SketchLine_3.startPoint())
SketchLine_4 = Sketch_1.addLine(50, 0, 0, 0)
SketchConstraintCoincidence_3 = Sketch_1.setCoincident(SketchLine_3.endPoint(), SketchLine_4.startPoint())
SketchConstraintCoincidence_4 = Sketch_1.setCoincident(SketchLine_4.endPoint(), SketchLine_1.startPoint())
SketchConstraintRigid_1 = Sketch_1.setFixed(SketchLine_1.startPoint())
SketchConstraintVertical_1 = Sketch_1.setVertical(SketchLine_1.result()[0])
SketchConstraintLength_1 = Sketch_1.setLength(SketchLine_4.result()[0], 50)
SketchConstraintLength_2 = Sketch_1.setLength(SketchLine_1.result()[0], 50)
SketchConstraintParallel_1 = Sketch_1.setParallel(SketchLine_1.result()[0], SketchLine_3.result()[0])
SketchConstraintParallel_2 = Sketch_1.setParallel(SketchLine_2.result()[0], SketchLine_4.result()[0])
SketchConstraintPerpendicular_1 = Sketch_1.setPerpendicular(SketchLine_1.result()[0], SketchLine_4.result()[0])
model.do()
Extrusion_1 = model.addExtrusion(Part_1_doc, [model.selection("FACE", "Sketch_1/Face-SketchLine_1r-SketchLine_2r-SketchLine_3r-SketchLine_4r")], model.selection(), 50, 0)
model.end()

model.exportToGEOM(Part_1_doc)
