## Copyright (C) 2014-20xx CEA/DEN, EDF R&D

UNSET(PYTHON_INCLUDE_DIRS)
UNSET(PYTHON_LIBRARIES)

IF(WIN32)
    IF(CMAKE_BUILD_TYPE STREQUAL "Debug")
      SET(PYTHON_LIBRARY_FILE "python27_d.lib")
    ElSE()
      SET(PYTHON_LIBRARY_FILE "python27.lib")
    ENDIF()
ElSE()
    SET(PYTHON_LIBRARY_FILE "libpython2.7.so")
ENDIF()

IF(WIN32)
  FILE(TO_CMAKE_PATH "$ENV{PYTHONHOME}/libs/${PYTHON_LIBRARY_FILE}" PATH_PYTHON_LIBRARY)
ElSE()
  FILE(TO_CMAKE_PATH "$ENV{PYTHONHOME}/lib/${PYTHON_LIBRARY_FILE}" PATH_PYTHON_LIBRARY)
ENDIF()
FILE(TO_CMAKE_PATH $ENV{PYTHON_INCLUDE} PATH_PYTHON_INCLUDE_DIR)

SET(PYTHON_INCLUDE_DIR ${PATH_PYTHON_INCLUDE_DIR} CACHE PATH "path to where Python.h is found" FORCE)
SET(PYTHON_LIBRARY ${PATH_PYTHON_LIBRARY} CACHE FILEPATH "path to the python library" FORCE)

FIND_PACKAGE(PythonLibs REQUIRED)
FIND_PACKAGE(PythonInterp REQUIRED)

INCLUDE_DIRECTORIES(${PYTHON_INCLUDE_DIR})
