

SET(GUI_ROOT_DIR $ENV{GUI_ROOT_DIR} CACHE PATH "Path to the Salome GUI directory")
IF(EXISTS ${GUI_ROOT_DIR})
	SET(HAVE_SALOME YES)
  
	FIND_LIBRARY(LightApp LightApp ${GUI_ROOT_DIR}/lib/salome)
	FIND_LIBRARY(OCCViewer OCCViewer ${GUI_ROOT_DIR}/lib/salome)
  
	SET(SALOME_GUI_INCLUDE ${GUI_ROOT_DIR}/include/salome)
	ADD_DEFINITIONS( -DHAVE_SALOME )
ENDIF(EXISTS ${GUI_ROOT_DIR})
