
IF(WIN32)
  INCLUDE_DIRECTORIES(${LIBXMLDIR}/include)
ELSE()
  INCLUDE_DIRECTORIES(${LIBXMLDIR}/include/libxml2)
ENDIF(WIN32)

LINK_DIRECTORIES (${LIBXMLDIR}/lib)

IF(WIN32)
    SET(LIBXML2_LIBRARIES ${LIBXMLDIR}/lib/libxml2.lib)
    INCLUDE_DIRECTORIES(${LIBXMLDIR}/include/libxml2)
ELSE()
    SET(LIBXML2_LIBRARIES ${LIBXMLDIR}/lib/libxml2.so)
    SET(LIBXML2_INCLUDE_DIR ${LIBXMLDIR}/include/libxml2)
	FIND_PACKAGE(LibXml2 REQUIRED)
	if(LIBXML2_FOUND)
	    message(STATUS "Found libxml2 ver. " ${LIBXML2_VERSION_STRING})
	    message(STATUS "LIBXML2_LIBRARIES " ${LIBXML2_LIBRARIES})
	    message(STATUS "LIBXML2_INCLUDE_DIR " ${LIBXML2_INCLUDE_DIR})
	endif(LIBXML2_FOUND)
	
	INCLUDE_DIRECTORIES(${LIBXML2_INCLUDE_DIR})
	ADD_DEFINITIONS(${LIBXML2_DEFINITIONS})
ENDIF()
LINK_DIRECTORIES (${LIBXMLDIR}/lib)

