CMAKE_MINIMUM_REQUIRED(VERSION 2.8.11)

FILE(TO_CMAKE_PATH $ENV{LIBXML2_INCLUDE_DIR} LIBXML2_INCLUDE_DIR)
 
FIND_PACKAGE(LibXml2 REQUIRED)
if(LIBXML2_FOUND)
    message(STATUS "Found libxml2 ver. " ${LIBXML2_VERSION_STRING})
    message(STATUS "LIBXML2_LIBRARIES " ${LIBXML2_LIBRARIES})
    message(STATUS "LIBXML2_INCLUDE_DIR " ${LIBXML2_INCLUDE_DIR})
endif(LIBXML2_FOUND)

INCLUDE_DIRECTORIES(${LIBXML2_INCLUDE_DIR})
ADD_DEFINITIONS(${LIBXML2_DEFINITIONS})
