// Copyright (C) 2014-20xx CEA/DEN, EDF R&D

/*
 * Events_Error.h
 *
 *  Created on: Apr 28, 2014
 *      Author: sbh
 */

#ifndef EVENTS_ERROR_H_
#define EVENTS_ERROR_H_

#include <Events.h>
#include <Events_Message.h>

#include <string>

/**\class Events_Error
 * \ingroup EventsLoop
 * \brief An error message event.
 *
 * Is generated by any algorithm or GUI of the application to inform the user about
 * the problem. In GUI mode all such errors are collected in the message log window.
 */
class EVENTS_EXPORT Events_Error : public Events_Message
{
  std::string myDescription;  ///< the description of the error

public:
  /// default destructor   
  virtual ~Events_Error();

  /// Identifier of this event (one for all errors)
  static Events_ID errorID();
  /// Specific error string
  const char* description() const;
  /// Allows to send an error quickly: it creates and sends the error object automatically
  static void send(const std::string& theDescription, const void* theSender = 0);

protected:
  /// Default constructor. Use "send" message for generation an error.
  Events_Error(const std::string& theDescription, const void* theSender = 0);
};

#endif /* EVENTS_ERROR_H_ */
