# Copyright (C) 2014-2021  CEA/DEN, EDF R&D
#
# This library is free software; you can redistribute it and/or
# modify it under the terms of the GNU Lesser General Public
# License as published by the Free Software Foundation; either
# version 2.1 of the License, or (at your option) any later version.
#
# This library is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
# Lesser General Public License for more details.
#
# You should have received a copy of the GNU Lesser General Public
# License along with this library; if not, write to the Free Software
# Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307 USA
#
# See http://www.salome-platform.org/ or email : webmaster.salome@opencascade.com
#

from SketchAPI import *

from salome.shaper import model

model.begin()
partSet = model.moduleDocument()
Part_1 = model.addPart(partSet)
Part_1_doc = Part_1.document()
Sketch_1 = model.addSketch(Part_1_doc, model.defaultPlane("XOZ"))
SketchLine_1 = Sketch_1.addLine(15, 17, 15, -3)
SketchLine_2 = Sketch_1.addLine(15, -3, 0, -3)
SketchConstraintCoincidence_1 = Sketch_1.setCoincident(SketchLine_1.endPoint(), SketchLine_2.startPoint())
SketchProjection_1 = Sketch_1.addProjection(model.selection("EDGE", "PartSet/OZ"), False)
SketchLine_3 = SketchProjection_1.createdFeature()
SketchLine_3.setName("SketchLine_4")
SketchLine_3.result().setName("SketchLine_4")
SketchConstraintVertical_1 = Sketch_1.setVertical(SketchLine_1.result())
SketchConstraintHorizontal_1 = Sketch_1.setHorizontal(SketchLine_2.result())
SketchConstraintCoincidence_2 = Sketch_1.setCoincident(SketchLine_2.endPoint(), SketchLine_3.result())
SketchConstraintCoincidence_2.setName("SketchConstraintCoincidence_4")
SketchArc_1 = Sketch_1.addArc(0, -8.980762113533162, 0, 21.01923788646684, 15, 17, True)
SketchConstraintCoincidence_3 = Sketch_1.setCoincident(SketchLine_3.result(), SketchArc_1.center())
SketchConstraintCoincidence_3.setName("SketchConstraintCoincidence_5")
SketchConstraintLength_1 = Sketch_1.setLength(SketchLine_2.result(), 15)
SketchConstraintLength_2 = Sketch_1.setLength(SketchLine_1.result(), 20)
SketchConstraintCoincidence_4 = Sketch_1.setCoincident(SketchArc_1.endPoint(), SketchLine_1.startPoint())
SketchConstraintCoincidence_4.setName("SketchConstraintCoincidence_7")
SketchConstraintRadius_1 = Sketch_1.setRadius(SketchArc_1.results()[1], 30)
SketchProjection_2 = Sketch_1.addProjection(model.selection("EDGE", "PartSet/OX"), False)
SketchLine_4 = SketchProjection_2.createdFeature()
SketchLine_4.setName("SketchLine_5")
SketchLine_4.result().setName("SketchLine_5")
SketchConstraintDistance_1 = Sketch_1.setDistance(SketchLine_2.startPoint(), SketchLine_4.result(), 3, True)
SketchLine_5 = Sketch_1.addLine(15, 0, 16, 0)
SketchLine_5.setName("SketchLine_6")
SketchLine_5.result().setName("SketchLine_6")
SketchConstraintCoincidence_5 = Sketch_1.setCoincident(SketchLine_5.startPoint(), SketchLine_1.result())
SketchConstraintCoincidence_5.setName("SketchConstraintCoincidence_8")
SketchConstraintCoincidence_6 = Sketch_1.setCoincident(SketchLine_5.endPoint(), SketchLine_4.result())
SketchConstraintCoincidence_6.setName("SketchConstraintCoincidence_9")
SketchLine_6 = Sketch_1.addLine(16, 0, 16, -3)
SketchLine_6.setName("SketchLine_7")
SketchLine_6.result().setName("SketchLine_7")
SketchConstraintCoincidence_7 = Sketch_1.setCoincident(SketchLine_5.endPoint(), SketchLine_6.startPoint())
SketchConstraintCoincidence_7.setName("SketchConstraintCoincidence_10")
SketchLine_7 = Sketch_1.addLine(16, -3, 15, -3)
SketchLine_7.setName("SketchLine_8")
SketchLine_7.result().setName("SketchLine_8")
SketchConstraintCoincidence_8 = Sketch_1.setCoincident(SketchLine_6.endPoint(), SketchLine_7.startPoint())
SketchConstraintCoincidence_8.setName("SketchConstraintCoincidence_11")
SketchConstraintCoincidence_9 = Sketch_1.setCoincident(SketchLine_1.endPoint(), SketchLine_7.endPoint())
SketchConstraintCoincidence_9.setName("SketchConstraintCoincidence_12")
SketchConstraintVertical_2 = Sketch_1.setVertical(SketchLine_6.result())
SketchConstraintCoincidence_10 = Sketch_1.setCoincident(SketchLine_5.startPoint(), SketchLine_4.result())
SketchConstraintCoincidence_10.setName("SketchConstraintCoincidence_13")
SketchConstraintCoincidence_11 = Sketch_1.setCoincident(SketchLine_7.startPoint(), SketchLine_2.result())
SketchConstraintCoincidence_11.setName("SketchConstraintCoincidence_14")
SketchConstraintLength_3 = Sketch_1.setLength(SketchLine_7.result(), 1)
SketchLine_8 = Sketch_1.addLine(15, 0, 0, 0)
SketchLine_8.setName("SketchLine_9")
SketchLine_8.result().setName("SketchLine_9")
SketchConstraintCoincidence_12 = Sketch_1.setCoincident(SketchLine_5.startPoint(), SketchLine_8.startPoint())
SketchConstraintCoincidence_12.setName("SketchConstraintCoincidence_15")
SketchConstraintCoincidence_13 = Sketch_1.setCoincident(SketchAPI_Line(SketchLine_3).startPoint(), SketchLine_8.endPoint())
SketchConstraintCoincidence_13.setName("SketchConstraintCoincidence_16")
SketchConstraintCoincidence_14 = Sketch_1.setCoincident(SketchArc_1.startPoint(), SketchLine_3.result())
SketchConstraintCoincidence_14.setName("SketchConstraintCoincidence_17")
model.do()
Edge_1_objects = [model.selection("EDGE", "Sketch_1/SketchArc_1_2"), model.selection("EDGE", "Sketch_1/SketchLine_1"), model.selection("EDGE", "Sketch_1/SketchLine_6"), model.selection("EDGE", "Sketch_1/SketchLine_7"), model.selection("EDGE", "Sketch_1/SketchLine_8"), model.selection("EDGE", "Sketch_1/SketchLine_2"), model.selection("EDGE", "Sketch_1/SketchLine_9")]
Edge_1 = model.addEdge(Part_1_doc, Edge_1_objects)
Revolution_1_objects = [model.selection("EDGE", "Edge_1_1"), model.selection("EDGE", "Edge_1_2"), model.selection("EDGE", "Edge_1_3"), model.selection("EDGE", "Edge_1_4"), model.selection("EDGE", "Edge_1_5"), model.selection("EDGE", "Edge_1_6"), model.selection("EDGE", "Edge_1_7")]
Revolution_1 = model.addRevolution(Part_1_doc, Revolution_1_objects, model.selection("EDGE", "PartSet/OZ"), 360, 0)
Sketch_2 = model.addSketch(Part_1_doc, model.standardPlane("XOZ"))
SketchProjection_3 = Sketch_2.addProjection(model.selection("VERTEX", "Sketch_1/SketchLine_2_EndVertex"), False)
SketchPoint_1 = SketchProjection_3.createdFeature()
SketchProjection_4 = Sketch_2.addProjection(model.selection("EDGE", "Sketch_1/SketchLine_2"), False)
SketchLine_9 = SketchProjection_4.createdFeature()
SketchLine_9.setName("SketchLine_11")
SketchLine_9.result().setName("SketchLine_11")
SketchLine_10 = Sketch_2.addLine(1.5, -3, -1.5, -3)
SketchLine_10.setName("SketchLine_10")
SketchLine_10.result().setName("SketchLine_10")
SketchConstraintCoincidence_15 = Sketch_2.setCoincident(SketchLine_10.startPoint(), SketchLine_9.result())
SketchConstraintCoincidence_15.setName("SketchConstraintCoincidence_18")
SketchLine_11 = Sketch_2.addLine(-1.5, -3, -1, -5)
SketchLine_11.setName("SketchLine_12")
SketchLine_11.result().setName("SketchLine_12")
SketchConstraintCoincidence_16 = Sketch_2.setCoincident(SketchLine_10.endPoint(), SketchLine_11.startPoint())
SketchConstraintCoincidence_16.setName("SketchConstraintCoincidence_19")
SketchLine_12 = Sketch_2.addLine(-1, -5, 1, -5)
SketchLine_12.setName("SketchLine_13")
SketchLine_12.result().setName("SketchLine_13")
SketchConstraintCoincidence_17 = Sketch_2.setCoincident(SketchLine_11.endPoint(), SketchLine_12.startPoint())
SketchConstraintCoincidence_17.setName("SketchConstraintCoincidence_20")
SketchLine_13 = Sketch_2.addLine(1, -5, 1.5, -3)
SketchLine_13.setName("SketchLine_14")
SketchLine_13.result().setName("SketchLine_14")
SketchConstraintCoincidence_18 = Sketch_2.setCoincident(SketchLine_12.endPoint(), SketchLine_13.startPoint())
SketchConstraintCoincidence_18.setName("SketchConstraintCoincidence_21")
SketchConstraintCoincidence_19 = Sketch_2.setCoincident(SketchLine_10.startPoint(), SketchLine_13.endPoint())
SketchConstraintCoincidence_19.setName("SketchConstraintCoincidence_22")
SketchConstraintHorizontal_2 = Sketch_2.setHorizontal(SketchLine_12.result())
SketchPoint_2 = Sketch_2.addPoint(-5.903605550615992e-26, -5)
SketchConstraintCoincidence_20 = Sketch_2.setCoincident(SketchPoint_2.coordinates(), SketchLine_12.result())
SketchConstraintCoincidence_20.setName("SketchConstraintCoincidence_24")
SketchConstraintMiddle_1 = Sketch_2.setMiddlePoint(SketchPoint_2.coordinates(), SketchLine_12.result())
SketchProjection_5 = Sketch_2.addProjection(model.selection("EDGE", "PartSet/OZ"), False)
SketchLine_14 = SketchProjection_5.createdFeature()
SketchLine_14.setName("SketchLine_16")
SketchLine_14.result().setName("SketchLine_16")
SketchConstraintCoincidence_21 = Sketch_2.setCoincident(SketchPoint_2.coordinates(), SketchLine_14.result())
SketchConstraintCoincidence_21.setName("SketchConstraintCoincidence_25")
SketchConstraintDistance_2 = Sketch_2.setDistance(SketchLine_11.endPoint(), SketchLine_10.result(), 2, True)
SketchConstraintLength_4 = Sketch_2.setLength(SketchLine_10.result(), 3)
SketchConstraintMiddle_2 = Sketch_2.setMiddlePoint(SketchAPI_Line(SketchLine_9).endPoint(), SketchLine_10.result())
SketchConstraintLength_5 = Sketch_2.setLength(SketchLine_12.result(), 2)
model.do()
Edge_2_objects = [model.selection("EDGE", "Sketch_2/SketchLine_12"), model.selection("EDGE", "Sketch_2/SketchLine_13"), model.selection("EDGE", "Sketch_2/SketchLine_14"), model.selection("EDGE", "Sketch_2/SketchLine_10")]
Edge_2 = model.addEdge(Part_1_doc, Edge_2_objects)
Extrusion_1_objects = [model.selection("EDGE", "Edge_2_1"), model.selection("EDGE", "Edge_2_2"), model.selection("EDGE", "Edge_2_3"), model.selection("EDGE", "Edge_2_4")]
Extrusion_1 = model.addExtrusion(Part_1_doc, Extrusion_1_objects, model.selection("EDGE", "PartSet/OY"), 3, 3)
Sketch_3 = model.addSketch(Part_1_doc, model.selection("FACE", "Revolution_1_6"))
SketchLine_15 = Sketch_3.addLine(-15, 0, -10, 2.951677693621839e-24)
SketchLine_15.setName("SketchLine_17")
SketchLine_15.result().setName("SketchLine_17")
SketchProjection_6 = Sketch_3.addProjection(model.selection("EDGE", "Revolution_1_6/Generated_Edge&Sketch_1/SketchLine_2_StartVertex"), False)
SketchCircle_1 = SketchProjection_6.createdFeature()
SketchConstraintCoincidence_22 = Sketch_3.setCoincident(SketchLine_15.startPoint(), SketchCircle_1.results()[1])
SketchConstraintCoincidence_22.setName("SketchConstraintCoincidence_26")
SketchLine_16 = Sketch_3.addLine(-10, 2.951677693621839e-24, -10, -3)
SketchLine_16.setName("SketchLine_18")
SketchLine_16.result().setName("SketchLine_18")
SketchConstraintCoincidence_23 = Sketch_3.setCoincident(SketchLine_15.endPoint(), SketchLine_16.startPoint())
SketchConstraintCoincidence_23.setName("SketchConstraintCoincidence_27")
SketchLine_17 = Sketch_3.addLine(-10, -3, -14.69693845669907, -3)
SketchLine_17.setName("SketchLine_19")
SketchLine_17.result().setName("SketchLine_19")
SketchConstraintCoincidence_24 = Sketch_3.setCoincident(SketchLine_16.endPoint(), SketchLine_17.startPoint())
SketchConstraintCoincidence_24.setName("SketchConstraintCoincidence_28")
SketchConstraintCoincidence_25 = Sketch_3.setCoincident(SketchLine_17.endPoint(), SketchCircle_1.results()[1])
SketchConstraintCoincidence_25.setName("SketchConstraintCoincidence_29")
SketchConstraintVertical_3 = Sketch_3.setVertical(SketchLine_16.result())
SketchConstraintCoincidence_26 = Sketch_3.setCoincident(SketchLine_15.result(), SketchAPI_Circle(SketchCircle_1).center())
SketchConstraintCoincidence_26.setName("SketchConstraintCoincidence_30")
SketchConstraintParallel_1 = Sketch_3.setParallel(SketchLine_15.result(), SketchLine_17.result())
SketchConstraintLength_6 = Sketch_3.setLength(SketchLine_15.result(), 5)
SketchConstraintLength_7 = Sketch_3.setLength(SketchLine_16.result(), 3)
SketchConstraintMirror_1 = Sketch_3.addMirror(SketchLine_15.result(), [SketchLine_16.result(), SketchLine_17.result()])
[SketchLine_18, SketchLine_19] = SketchConstraintMirror_1.mirrored()
SketchLine_19.setName("SketchLine_21")
SketchLine_19.result().setName("SketchLine_21")
SketchLine_18.setName("SketchLine_20")
SketchLine_18.result().setName("SketchLine_20")
SketchLine_20 = Sketch_3.addLine(-1.5, -2, 2, -2)
SketchLine_20.setName("SketchLine_22")
SketchLine_20.result().setName("SketchLine_22")
SketchLine_21 = Sketch_3.addLine(2, -2, 2, 2)
SketchLine_21.setName("SketchLine_23")
SketchLine_21.result().setName("SketchLine_23")
SketchConstraintCoincidence_27 = Sketch_3.setCoincident(SketchLine_20.endPoint(), SketchLine_21.startPoint())
SketchConstraintCoincidence_27.setName("SketchConstraintCoincidence_31")
SketchLine_22 = Sketch_3.addLine(2, 2, -1.5, 2)
SketchLine_22.setName("SketchLine_24")
SketchLine_22.result().setName("SketchLine_24")
SketchConstraintCoincidence_28 = Sketch_3.setCoincident(SketchLine_21.endPoint(), SketchLine_22.startPoint())
SketchConstraintCoincidence_28.setName("SketchConstraintCoincidence_32")
SketchProjection_7 = Sketch_3.addProjection(model.selection("EDGE", "PartSet/OX"), False)
SketchLine_23 = SketchProjection_7.createdFeature()
SketchLine_23.setName("SketchLine_25")
SketchLine_23.result().setName("SketchLine_25")
SketchConstraintCoincidence_29 = Sketch_3.setCoincident(SketchLine_15.startPoint(), SketchLine_23.result())
SketchConstraintCoincidence_29.setName("SketchConstraintCoincidence_33")
SketchConstraintHorizontal_3 = Sketch_3.setHorizontal(SketchLine_22.result())
SketchConstraintHorizontal_4 = Sketch_3.setHorizontal(SketchLine_20.result())
SketchConstraintVertical_4 = Sketch_3.setVertical(SketchLine_21.result())
SketchArc_2 = Sketch_3.addArc(0, 0, -1.5, -2, -1.5, 2, True)
SketchConstraintCoincidence_30 = Sketch_3.setCoincident(SketchAPI_Circle(SketchCircle_1).center(), SketchArc_2.center())
SketchConstraintCoincidence_30.setName("SketchConstraintCoincidence_34")
SketchConstraintCoincidence_31 = Sketch_3.setCoincident(SketchArc_2.startPoint(), SketchLine_20.startPoint())
SketchConstraintCoincidence_31.setName("SketchConstraintCoincidence_35")
SketchConstraintCoincidence_32 = Sketch_3.setCoincident(SketchArc_2.endPoint(), SketchLine_22.endPoint())
SketchConstraintCoincidence_32.setName("SketchConstraintCoincidence_36")
SketchPoint_3 = Sketch_3.addPoint(2, 0)
SketchConstraintCoincidence_33 = Sketch_3.setCoincident(SketchPoint_3.coordinates(), SketchLine_21.result())
SketchConstraintCoincidence_33.setName("SketchConstraintCoincidence_37")
SketchConstraintCoincidence_34 = Sketch_3.setCoincident(SketchPoint_3.coordinates(), SketchLine_23.result())
SketchConstraintCoincidence_34.setName("SketchConstraintCoincidence_38")
SketchConstraintMiddle_3 = Sketch_3.setMiddlePoint(SketchPoint_3.coordinates(), SketchLine_21.result())
SketchLine_24 = Sketch_3.addLine(-1.5, -2, -1.5, 2)
SketchLine_24.setName("SketchLine_26")
SketchLine_24.result().setName("SketchLine_26")
SketchLine_24.setAuxiliary(True)
SketchConstraintCoincidence_35 = Sketch_3.setCoincident(SketchLine_20.startPoint(), SketchLine_24.startPoint())
SketchConstraintCoincidence_35.setName("SketchConstraintCoincidence_39")
SketchConstraintCoincidence_36 = Sketch_3.setCoincident(SketchLine_22.endPoint(), SketchLine_24.endPoint())
SketchConstraintCoincidence_36.setName("SketchConstraintCoincidence_40")
SketchProjection_8 = Sketch_3.addProjection(model.selection("VERTEX", "Sketch_2/SketchLine_10_EndVertex"), False)
SketchPoint_4 = SketchProjection_8.createdFeature()
SketchConstraintCoincidence_37 = Sketch_3.setCoincident(SketchAPI_Point(SketchPoint_4).coordinates(), SketchLine_24.result())
SketchConstraintCoincidence_37.setName("SketchConstraintCoincidence_41")
SketchConstraintLength_8 = Sketch_3.setLength(SketchLine_24.result(), 4)
SketchProjection_9 = Sketch_3.addProjection(model.selection("VERTEX", "Sketch_2/SketchLine_10_StartVertex"), False)
SketchPoint_5 = SketchProjection_9.createdFeature()
SketchConstraintDistance_3 = Sketch_3.setDistance(SketchAPI_Point(SketchPoint_5).coordinates(), SketchLine_21.result(), 0.5, True)
SketchLine_25 = Sketch_3.addLine(-7.5, -7.382311001750988e-22, -7.5, -3)
SketchLine_25.setName("SketchLine_27")
SketchLine_25.result().setName("SketchLine_27")
SketchConstraintVertical_5 = Sketch_3.setVertical(SketchLine_25.result())
SketchConstraintCoincidence_38 = Sketch_3.setCoincident(SketchLine_25.startPoint(), SketchLine_15.result())
SketchConstraintCoincidence_38.setName("SketchConstraintCoincidence_42")
SketchConstraintCoincidence_39 = Sketch_3.setCoincident(SketchLine_25.endPoint(), SketchLine_17.result())
SketchConstraintCoincidence_39.setName("SketchConstraintCoincidence_43")
SketchLine_26 = Sketch_3.addLine(-7.5, -7.382311001750988e-22, -2.500000000000019, -5.187200122832181e-16)
SketchLine_26.setName("SketchLine_28")
SketchLine_26.result().setName("SketchLine_28")
SketchConstraintCoincidence_40 = Sketch_3.setCoincident(SketchLine_25.startPoint(), SketchLine_26.startPoint())
SketchConstraintCoincidence_40.setName("SketchConstraintCoincidence_44")
SketchConstraintCoincidence_41 = Sketch_3.setCoincident(SketchLine_26.endPoint(), SketchArc_2.results()[1])
SketchConstraintCoincidence_41.setName("SketchConstraintCoincidence_45")
SketchConstraintHorizontal_5 = Sketch_3.setHorizontal(SketchLine_26.result())
SketchConstraintDistance_4 = Sketch_3.setDistance(SketchLine_16.startPoint(), SketchLine_25.result(), 2.5, True)
SketchLine_27 = Sketch_3.addLine(2, 0, 11, 0)
SketchLine_27.setName("SketchLine_29")
SketchLine_27.result().setName("SketchLine_29")
SketchConstraintCoincidence_42 = Sketch_3.setCoincident(SketchPoint_3.coordinates(), SketchLine_27.startPoint())
SketchConstraintCoincidence_42.setName("SketchConstraintCoincidence_46")
SketchConstraintCoincidence_43 = Sketch_3.setCoincident(SketchLine_27.endPoint(), SketchLine_23.result())
SketchConstraintCoincidence_43.setName("SketchConstraintCoincidence_47")
SketchLine_28 = Sketch_3.addLine(15, 0, 14, 0)
SketchLine_28.setName("SketchLine_30")
SketchLine_28.result().setName("SketchLine_30")
SketchProjection_10 = Sketch_3.addProjection(model.selection("VERTEX", "[Revolution_1_6/Revolution_1_6&Sketch_1/SketchLine_2]"), False)
SketchPoint_6 = SketchProjection_10.createdFeature()
SketchConstraintCoincidence_44 = Sketch_3.setCoincident(SketchLine_28.startPoint(), SketchPoint_6.result())
SketchConstraintCoincidence_44.setName("SketchConstraintCoincidence_48")
SketchConstraintCoincidence_45 = Sketch_3.setCoincident(SketchLine_28.endPoint(), SketchLine_23.result())
SketchConstraintCoincidence_45.setName("SketchConstraintCoincidence_49")
SketchConstraintDistance_5 = Sketch_3.setDistance(SketchLine_27.endPoint(), SketchLine_28.endPoint(), 3, True)
SketchConstraintLength_9 = Sketch_3.setLength(SketchLine_28.result(), 1)
SketchLine_29 = Sketch_3.addLine(11, 0, 11, -2.000000000000004)
SketchLine_29.setName("SketchLine_31")
SketchLine_29.result().setName("SketchLine_31")
SketchConstraintCoincidence_46 = Sketch_3.setCoincident(SketchLine_27.endPoint(), SketchLine_29.startPoint())
SketchConstraintCoincidence_46.setName("SketchConstraintCoincidence_50")
SketchLine_30 = Sketch_3.addLine(9.500000000000002, 2.627360613063856e-19, 9.5, -2.000000000000004)
SketchLine_30.setName("SketchLine_32")
SketchLine_30.result().setName("SketchLine_32")
SketchConstraintCoincidence_47 = Sketch_3.setCoincident(SketchLine_30.startPoint(), SketchLine_27.result())
SketchConstraintCoincidence_47.setName("SketchConstraintCoincidence_51")
SketchLine_31 = Sketch_3.addLine(8, -1.882265929199326e-20, 8, -2.000000000000004)
SketchLine_31.setName("SketchLine_33")
SketchLine_31.result().setName("SketchLine_33")
SketchConstraintCoincidence_48 = Sketch_3.setCoincident(SketchLine_31.startPoint(), SketchLine_27.result())
SketchConstraintCoincidence_48.setName("SketchConstraintCoincidence_52")
SketchLine_32 = Sketch_3.addLine(5, -3.396138881322731e-22, 5, -2.000000000000004)
SketchLine_32.setName("SketchLine_34")
SketchLine_32.result().setName("SketchLine_34")
SketchConstraintCoincidence_49 = Sketch_3.setCoincident(SketchLine_32.startPoint(), SketchLine_27.result())
SketchConstraintCoincidence_49.setName("SketchConstraintCoincidence_53")
SketchLine_33 = Sketch_3.addLine(5, -2.000000000000004, 11, -2.000000000000004)
SketchLine_33.setName("SketchLine_35")
SketchLine_33.result().setName("SketchLine_35")
SketchLine_33.setAuxiliary(True)
SketchConstraintCoincidence_50 = Sketch_3.setCoincident(SketchLine_32.endPoint(), SketchLine_33.startPoint())
SketchConstraintCoincidence_50.setName("SketchConstraintCoincidence_54")
SketchConstraintCoincidence_51 = Sketch_3.setCoincident(SketchLine_29.endPoint(), SketchLine_33.endPoint())
SketchConstraintCoincidence_51.setName("SketchConstraintCoincidence_55")
SketchConstraintVertical_6 = Sketch_3.setVertical(SketchLine_32.result())
SketchConstraintVertical_7 = Sketch_3.setVertical(SketchLine_31.result())
SketchConstraintVertical_8 = Sketch_3.setVertical(SketchLine_30.result())
SketchConstraintHorizontal_6 = Sketch_3.setHorizontal(SketchLine_33.result())
SketchConstraintCoincidence_52 = Sketch_3.setCoincident(SketchLine_31.endPoint(), SketchLine_33.result())
SketchConstraintCoincidence_52.setName("SketchConstraintCoincidence_56")
SketchConstraintCoincidence_53 = Sketch_3.setCoincident(SketchLine_30.endPoint(), SketchLine_33.result())
SketchConstraintCoincidence_53.setName("SketchConstraintCoincidence_57")
SketchConstraintDistance_6 = Sketch_3.setDistance(SketchLine_20.endPoint(), SketchLine_32.result(), 3, True)
SketchConstraintDistance_7 = Sketch_3.setDistance(SketchLine_32.endPoint(), SketchLine_31.result(), 3, True)
SketchConstraintDistance_8 = Sketch_3.setDistance(SketchLine_31.endPoint(), SketchLine_30.result(), 1.5, True)
SketchConstraintDistance_9 = Sketch_3.setDistance(SketchLine_30.endPoint(), SketchLine_29.result(), 1.5, True)
SketchConstraintCoincidence_54 = Sketch_3.setCoincident(SketchLine_32.endPoint(), SketchLine_20.result())
SketchConstraintCoincidence_54.setName("SketchConstraintCoincidence_58")
SketchConstraintMirror_2_objects = [SketchLine_32.result(), SketchLine_31.result(), SketchLine_30.result(), SketchLine_29.result()]
SketchConstraintMirror_2 = Sketch_3.addMirror(SketchLine_23.result(), SketchConstraintMirror_2_objects)
[SketchLine_34, SketchLine_35, SketchLine_36, SketchLine_37] = SketchConstraintMirror_2.mirrored()
SketchLine_37.setName("SketchLine_39")
SketchLine_37.result().setName("SketchLine_39")
SketchLine_36.setName("SketchLine_38")
SketchLine_36.result().setName("SketchLine_38")
SketchLine_35.setName("SketchLine_37")
SketchLine_35.result().setName("SketchLine_37")
SketchLine_34.setName("SketchLine_36")
SketchLine_34.result().setName("SketchLine_36")
model.do()
model.do()
model.end()

assert(model.checkPythonDump())
